{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# toy problem 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Generate data\n",
    "\n",
    "train_data size (100,500,128,128)\n",
    "\n",
    "validation size (10,500,128,128)\n",
    "\n",
    "test size (10,500,128,128)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# import sys\n",
    "import numpy as np\n",
    "# import scipy as sp\n",
    "# from scipy import integrate\n",
    "from tqdm.notebook import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.animation as animation\n",
    "# import torch\n",
    "\n",
    "# module_path = os.path.abspath(os.path.join('../src/'))\n",
    "# if module_path not in sys.path:\n",
    "#     sys.path.append(module_path)\n",
    "    \n",
    "    \n",
    "# import utils"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_data(n_points, file_name, data_dir = './data/toy2c', n_time_steps = 500, dim = 128, num_periods_big = 8, w0=0.5, w1=1.0, width_small = 64):\n",
    "    \"\"\"\n",
    "    Makes data for toy2c\n",
    "    \n",
    "    Inputs:\n",
    "    n_points: int, how many data points \n",
    "    file_name: str, name of file to save\n",
    "    data_dir = './data/toy2': str, directory of where to store\n",
    "    n_time_steps = 500: int, how many time steps per data point\n",
    "    dim = 128: int, how many data points per dim, while be same in both x and y directions\n",
    "    num_periods_big = 8: int, how many periods of the slow scale\n",
    "    w0 = 0.5: float, frequency of slow scale\n",
    "    w1 = 1.0: float, frequency of fast scale\n",
    "    width_small = 8: width of small (fast) scale\n",
    "    \n",
    "    Output: \n",
    "    data: size (n_points,n_time_steps,dim, dim) will be returned and saved to file data_dir+file_name\n",
    "    \n",
    "    \"\"\"\n",
    "    print(width_small)\n",
    "    print(\"Making data\")\n",
    "    x = np.arange(dim)\n",
    "    y = np.arange(dim)\n",
    "    data = np.zeros((n_points, n_time_steps, dim, dim))\n",
    "\n",
    "    for i in tqdm(range(n_points)):\n",
    "        t_start = np.random.uniform(high=4*np.pi)\n",
    "        t = np.linspace(t_start, num_periods_big*4*np.pi + t_start, n_time_steps)\n",
    "\n",
    "\n",
    "        xgrid, ygrid, tgrid = np.meshgrid(x, y, t)\n",
    "\n",
    "        Phi = np.cos(w0*tgrid)\n",
    "\n",
    "        Phi[1:3, 0:2,:] = np.cos(w1*tgrid[1:3, 0:2,:]+np.pi/4)\n",
    "        scaled_Phi = (Phi.T - Phi.min()) / (Phi.max() - Phi.min())\n",
    "        data[i] = scaled_Phi\n",
    "\n",
    "    print(\"making done, saving to \", os.path.join(data_dir, file_name))\n",
    "    np.save(os.path.join(data_dir, file_name), data)\n",
    "    print(\"done\")\n",
    "    \n",
    "    return data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "75989c4ad6a04d82bccde7a4a0c363be",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/100 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "making done, saving to  ../data/toy2c/train_data.npy\n",
      "done\n",
      "(100, 500, 4, 4)\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAUAAAAD8CAYAAAAG730QAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAW7klEQVR4nO3df6xfdX3H8eeLWkXUBrFuVEBhWadhRsE1Bccy8ddsOzL8gyxFxcVobjQyYZFs6BKW/bc/jNkcSNcom2REtgm6xhUrMxglArbUUikV1+EyKsWu/K6w0nvva3+cc5vvvv3e+z235/Tec3peD3LS7/eczzmfz72k734+5/NLtomI6KOTFrsAERGLJQEwInorATAieisBMCJ6KwEwInorATAieusldW6WdBrwT8DZwH8Bf2j7qRHp/gt4DpgCJm2vqpNvREQT6tYArwW+Y3sl8J3y+2zeafu8BL+IaIu6AfBS4Cvl568A76/5vIiIBaM6M0EkPW371IHvT9l+9Yh0PwOeAgz8ne2NczxzApgAWMKS3zqFZcdcvrb6jbc8v9hFiHn66c5TFrsIx8X/8kte9CHVecb73vkKP/HkVKW09+88tMX2mjr5NWnsO0BJ/w6cPuLSn88jn4tsPybpV4A7Jf3E9vdGJSyD40aAZTrNF+jd88imG7Zs2bHYRYh5et/rzlvsIhwX9/k7tZ9x4Mkp7ttyZqW0S1f85/LaGTZobAC0/Z7Zrkn6haQVtvdJWgHsn+UZj5V/7pf0dWA1MDIARkTXmClPL3Yhjkndd4CbgD8qP/8R8K/DCSS9QtKrZj4Dvwc8WDPfiGgJA9O40tE2dQPgXwHvlfQfwHvL70h6naTNZZpfBe6W9ADwQ+DfbH+rZr4R0SLTFf8bR9IaSQ9L2iPpqFElkj4oaWd5/EDSW8vzZ0m6S9JuSbskXVWl3LXGAdp+AjjqJV3Z5F1Xfn4EeGudfCKivYw53EATWNIS4AaKytReYKukTbYfGkj2M+Adtp+StJaiv+ACYBL4tO3tZYvzfkl3Dt17lFoBMCLCwFQzzdvVwJ6y0oSkWymG2h0JYrZ/MJD+XuDM8vw+YF/5+TlJu4EzBu8dJQEwImqbx/u95ZK2DXzfODAs7gzg0YFreylqd7P5KHDH8ElJZwPnA/eNK0wCYETUYmCq+njiA3PMBhs1HnHkgyW9kyIA/s7Q+VcCtwFX2352XGESACOitoYGwewFzhr4fibw2HAiSW8BvgSsLfshZs4vpQh+t9i+vUqGCYARUYtxU+8AtwIrJZ0D/BxYD3xgMIGk1wO3A1fY/unAeQFfBnbb/nzVDBMAI6IWGw43EP9sT0q6EtgCLAFusr1L0sfL6xuA64DXAF8sYt6R1aUuAq4AfixpR/nIz9rezBwSACOiJjE18vXd/JUBa/PQuQ0Dnz8GfGzEfXcz+h3inBIAI6IWA9Ptm+RRSQJgRNTWVA1woSUARkQtxUDoBMCI6CEDh93N7YUSACOiFiOmOrq/WgJgRNQ27TSBI6KH8g4wInpMTOUdYET0UbEidAJgRPSQLV70ksUuxjFJAIyI2qY7+g6wkXprhXX8JekL5fWdkt7WRL4RsfiKTpCTKh1tU7sGWHEd/7XAyvK4ALiRuVd6jYjO6G4nSBOlPrKOv+0XgZl1/AddCtzswr3AqeU+whHRcTOdIFWOtmmiRKPW8T/jGNJEREdNWZWOtmmiE6TKOv7zWet/ApgAOJlT6pUsIo47Iw67m/2pTZS6yjr+ldb6Byh3iNoIsEyndXSVsYj+mOkE6aImSn1kHX9JL6VYx3/TUJpNwIfL3uALgWfKfTwjouNMtebvCdkErriO/2ZgHbAHeB74SN18I6I92tjBUUUjDfcK6/gb+GQTeUVEu9h0dhhMN99cRkRrFJ0gmQoXET3V1U6QBMCIqMUoC6JGRH+lBhgRvVTsC5wAGBG9pCyJHxH9VGyLmV7giOghW2kCR0R/ZSB0RPRSsR5gN98BdjNsR0SLFCtCVznGPmn89hofLLfV2CnpB5LeWvXeUVIDjIhaimEw9WuAFbfX+BnwDttPSVpLsXTeBRXvPUoCYETU0uBc4CPbawBImtle40gQs/2DgfT3UqwtWuneUdIEjoja5rEnyHJJ2waOiYHHzHfrjI8CdxzjvUBqgBFRU7EcVuUm8AHbq2a5Np+tM95JEQB/Z773DkoAjIjaGloModLWGZLeAnwJWGv7ifncOyxN4IiopVgN5qRKxxhjt9eQ9HrgduAK2z+dz72jpAYYEbUUU+Hq16Uqbq9xHfAa4IuSACZtr5rt3nF5JgBGRE3NTYWrsL3Gx4CPVb13nEZKXWHw4sWSnpG0ozyuayLfiGiHaVTpaJvaNcB5DED8vu1L6uYXEe0yz17gVmmiCXxMAxAj4sTR1dVgmih11QGIb5f0gKQ7JP3mbA+TNDEzSPIwhxooXkQcTzN7glQ52qaJGmCVAYjbgTfYPihpHfANYOWoh9neSDG/j2U6bexAxohYXAYme1wDHDsA0faztg+WnzcDSyUtbyDviGiBhsYBLrgmSlRl8OLpKgftSFpd5vvEUU+KiO6p2Pw9IZvAFQcvXgZ8QtIk8AKw3naatxEngC4viNrIQOgKgxevB65vIq+IaJ821u6qyEyQiKilqQVRF0MCYETUYsTkdPs6OKpIAIyI2nr9DjAiesxpAkdET+UdYET0WgJgRPSSEVPpBImIvkonSET0ktMJEhF95gTAiOindi50UEUCYETUlhpgRPSSDVPTCYAR0VPpBY6IXjJpAkdEb6UTJCJ6rKvruycARkRtXW0CNzKBT9JNkvZLenCW65L0BUl7JO2U9LYm8o2IxVf0Ap9U6Wibpkr0D8CaOa6vpdgHeCUwAdzYUL4R0QJ2taNtGgmAtr8HPDlHkkuBm124FzhV0oom8o6IxWer0tE2C/UO8Azg0YHve8tz+4YTSpqgqCVyMqcsSOEi4tiZdga3KhaqUT7qtzOyQmx7o+1Vtlct5WXHuVgR0QRXPMaRtEbSw2V/wbUjrr9J0j2SDkm6Zujan0jaJelBSV+VdPK4/BYqAO4Fzhr4fibw2ALlHRHHk8HTqnTMRdIS4AaKPoNzgcslnTuU7EngU8Dnhu49ozy/yvabgSXA+nFFX6gAuAn4cNkbfCHwjO2jmr8R0U0NvQNcDeyx/YjtF4FbKfoPBvLxfttbgcMj7n8J8HJJLwFOoUIlq5F3gJK+ClwMLJe0F/gLYGlZ4A3AZmAdsAd4HvhIE/lGRDvMo4d3uaRtA9832t5Yfh7VV3BBtfz9c0mfA/4beAH4tu1vj7uvkQBo+/Ix1w18som8IqJd5jkX+IDtVbNcq9xXcNSN0qspaovnAE8D/yLpQ7b/ca772jcyMSK6xYBV7Zhbnb6C9wA/s/0/tg8DtwO/Pe6mBMCIqK2hgdBbgZWSzpH0UopOjE0Vi/DfwIWSTpEk4N3A7nE3ZS5wRNQ0voe3CtuTkq4EtlD04t5ke5ekj5fXN0g6HdgGLAOmJV0NnGv7PklfA7YDk8CPgI2j8hmUABgR9TU0zc32ZopO08FzGwY+P07RNB51719QdMBWlgAYEfW4u6vBJABGRH0tXOigigTAiGhAaoAR0VfTi12AY5MAGBH1zIwD7KAEwIiorY2LnVaRABgR9SUARkRvpQkcEX2l1AAjopcsaGAq3GJIAIyI+lIDjIjeSgCMiN5KAIyIXurwQOhGFkSVdJOk/ZIenOX6xZKekbSjPK5rIt+IaAe52tE2TdUA/wG4Hrh5jjTft31JQ/lFRJu0MLhV0dSmSN+TdHYTz4qI7mlj7a6KhXwH+HZJD1BscnKN7V2jEkmaACYATuaUBSzewnnf685b7CJENKuj7wAXKgBuB95g+6CkdcA3gJWjEpZ7hG4EWKbTOvrvSkSPmM42gRdkVzjbz9o+WH7eDCyVtHwh8o6IBeCKR8ssSA2w3MnpF7YtaTVF4H1iIfKOiONPfV4QVdJXgYuB5ZL2UuzMtBSO7Oh0GfAJSZPAC8B6u6sriEXEUTr6t7mpXuDLx1y/nmKYTEScYNo6xq+KzASJiPrSCxwRvZUaYET0VZrAEdFP7nkvcET0XGqAEdFbCYAR0VddfQe4IFPhIiKqkLRG0sOS9ki6dsT1N0m6R9IhSdcMXTtV0tck/UTSbklvH5dfaoARUV8DNUBJS4AbgPcCe4GtkjbZfmgg2ZPAp4D3j3jE3wDfsn2ZpJfC+OWkUgOMiHrKXuAqxxirgT22H7H9InArcOn/y8reb3srcHjwvKRlwO8CXy7TvWj76XEZJgBGRH3VV4NZLmnbwDEx8JQzgEcHvu8tz1Xxa8D/AH8v6UeSviTpFeNuSgCMiFrEvPYEOWB71cCxcehRw6o2rl8CvA240fb5wC+Bo94hDksAjIj6mlkPcC9w1sD3MylWkK9iL7DX9n3l969RBMQ5JQBGRD0Va38VhspsBVZKOqfsxFgPbKpUBPtx4FFJbyxPvRt4aI5bgPQCR0QTGpgKZ3tS0pXAFmAJcJPtXZI+Xl7fUC6uvA1YBkxLuho41/azwB8Dt5TB8xHgI+PyTACMiNqaGghdbpmxeejchoHPj1M0jUfduwNYNZ/8EgAjor6OzgRJAIyIelq64VEVtTtBJJ0l6a5y6skuSVeNSCNJXyint+yUNLZ3JiK6o6FOkAXXRA1wEvi07e2SXgXcL+nOoekrayn2AV4JXADcWP4ZESeCFga3KmrXAG3vs729/PwcsJujR29fCtzswr3AqZJW1M07ItqhoalwC67RcYCSzgbOB+4bulR5ioukiZlpMoc51GTxIuJ4qDoIuoW1xMYCoKRXArcBV5djcv7f5RG3jPx12N44M01mKS9rqngRcZxoHkfbNLUx+lKK4HeL7dtHJKkzxSUi2q6FtbsqmugFFsUSNLttf36WZJuAD5e9wRcCz9jeVzfviGiHPvcCXwRcAfxY0o7y3GeB18ORUdybgXXAHuB5KkxRiYgOaWFwq6J2ALR9N2Oa97YNfLJuXhHRQtkWMyJ6ra81wIiINr7fqyIBMCLqSwCMiL5KDTAi+sk0siDqYkgAjIhaZjZF6qIEwIioLwEwIvpK7mYETACMiHpautJLFQmAEVFb3gFGRG9lKlxE9FdqgBHRSy1d6qqKBMCIqC8BMCL6KAOhI6LXNN3NCJgAGBH1ZBxgRPRZV4fBNLEp0lmS7pK0W9IuSVeNSHOxpGck7SiP6+rmGxEt0tF9gZuoAU4Cn7a9XdKrgPsl3Wn7oaF037d9SQP5RUTLdLUTpHYN0PY+29vLz88Bu4Ez6j43IjrCgF3tGEPSGkkPS9oj6doR198k6R5JhyRdM+L6Ekk/kvTNKkWvHQCHMj8bOB+4b8Tlt0t6QNIdkn5zjmdMSNomadthDjVZvIg4TjRd7ZjzGdIS4AZgLXAucLmkc4eSPQl8CvjcLI+5iqISVkljAVDSK4HbgKttPzt0eTvwBttvBf4W+MZsz7G90fYq26uW8rKmihcRx8nMOMAGNkZfDeyx/YjtF4FbgUsHE9jeb3srcPiockhnAr8PfKlq2RsJgJKWUgS/W2zfPnzd9rO2D5afNwNLJS1vIu+IWGRVm79FE3j5TAuvPCYGnnQG8OjA973M73XaXwN/yjwW6K/dCSJJwJeB3bY/P0ua04Ff2Lak1RSB94m6eUdEO8yjE+SA7VWzPWbEuUpPlnQJsN/2/ZIurlqYJnqBLwKuAH4saUd57rPA6wFsbwAuAz4haRJ4AVhvd3QJ2Yg4WjN/m/cCZw18PxN4rOK9FwF/IGkdcDKwTNI/2v7QXDfVDoC272Z05B5Mcz1wfd28IqKdGhoGsxVYKekc4OfAeuADVW60/RngM1CMOwauGRf8IDNBIqIuA1P1I6DtSUlXAluAJcBNtndJ+nh5fUP5Om0bsAyYlnQ1cO6IjtdKEgAjoramBkKXnaSbh85tGPj8OEXTeK5nfBf4bpX8EgAjor6OvtJPAIyI2ro6FS4BMCLqaelCB1UkAEZELQLUQCfIYkgAjIjalHeAEdFLaQJHRH9VW+qqjRIAI6K29AJHRH+lBhgRveT0AkdEn3Uz/iUARkR9GQYTEf2VABgRvWTmsQh9uyQARkQtwmkCR0SPTXezClh7VzhJJ0v6Ybnn7y5JfzkijSR9odzseKekt9XNNyJaYqYJXOVomSZqgIeAd9k+WG6PebekO2zfO5BmLbCyPC4Abiz/jIgTQFebwLVrgC4cLL8uLY/h38alwM1l2nuBUyWtqJt3RLRE9X2BW6WpjdGXlFti7gfutH3fUJK6Gx5HRGvNa2P0VmkkANqesn0exWYlqyW9eShJ5Q2PJU3M7Bp/mENNFC8ijqeZXeGqHC3TSACcYftpit2Y1gxdqrzhse2NtlfZXrWUlzVZvIg4TmRXOtqmiV7g10o6tfz8cuA9wE+Gkm0CPlz2Bl8IPGN7X928I6IlOtoEbqIXeAXwFUlLKALqP9v+5uBmxhT7fK4D9gDPAx9pIN+IaAMD0+0LblXUDoC2dwLnjzg/uJmxgU/WzSsi2qidtbsqMhMkIupLAIyIXjIw1cJpHhUkAEZETQYnAEZEX6UJHBG91OFe4EYHQkdETzU0DlDSGkkPlytHXTvi+psk3SPpkKRrBs6fJekuSbvLVamuqlLs1AAjor4GmsDlWOIbgPdSzB7bKmmT7YcGkj0JfAp4/9Dtk8CnbW+X9Crgfkl3Dt17lNQAI6IeG6amqh1zWw3ssf2I7ReBWylWkhrIyvttbwUOD53fZ3t7+fk5YDcVFlxJAIyI+qo3gZfPLHZSHhMDT2lk1ShJZ1NMzhheleooaQJHRH3Vm8AHbK+a5VrlVaNmI+mVwG3A1bafHZc+ATAianJTvcCVV40apVyR/jbgFtu3V7knATAi6jG4mYHQW4GVks4Bfg6sBz5Q5UZJAr4M7Lb9+aoZJgBGRH0NTIWzPSnpSmALsAS4yfauwZWlJJ0ObAOWAdOSrgbOBd4CXAH8uFydHuCztjfPlWcCYETUYze2LWYZsDYPnRtcWepxiqbxsLsZ/Q5xTgmAEVFfpsJFRF+5oxujJwBGRE1ZEDUi+qrDiyEkAEZELQY8fppbKzWxK9zJkn4o6YFyFYa/HJHmYknPSNpRHtfVzTciWsLlgqhVjpZpogZ4CHiX7YPlSOy7Jd1h+96hdN+3fUkD+UVEy7ivTeByx7eD5del5dHN30ZEHJsW1u6qkJtbx+t+4NeBG2z/2dD1iynm6O2lmNt3je1dszxrAphZIeKNwMO1C1jNcuDAAuW1kPJzdc9C/mxvsP3aOg+Q9C2KMldxwPaaOvk1qZEAeORh0qnA14E/tv3gwPllwHTZTF4H/I3tlY1l3ABJ2+ZYpaKz8nN1z4n8s7VNo+sB2n4a+C6wZuj8s7YPlp83A0slVf0XIyLiuGiiF/i1Zc0PSS8H3gP8ZCjN6eVqDUhaXeb7RN28IyLqaKIXeAXwlfI94EnAP9v+5uAKDsBlwCckTQIvAOvdZNu7GRsXuwDHSX6u7jmRf7ZWafQdYEREl2RPkIjorQTAiOit3gfAcRsxd5WkmyTtl/Tg+NTdcawbYLddlSml0bxevwMsO25+ysBGzMDl4zZT7gJJv0sxQ+dm229e7PI0RdIKYMXgBtjA+7v+/6wcJfGKwSmlwFUjppRGg/peAxy7EXNX2f4e8ORil6Npx7oBdtu5kCmlC6zvAbCRjZhjccxnA+wukLSk3NBnP3Cn7RPi52qzvgfA2hsxx+KY7wbYXWB7yvZ5FJv+rJZ0wry6aKu+B8BaGzHH4jiWDbC7ZLYppdG8vgfAIxsxS3opxUbMmxa5TDGHY90Au+2qTCmN5vU6ANqeBGY2Yt5NMY1v5DJdXSPpq8A9wBsl7ZX00cUuU0MuotgA+10DK4yvW+xCNWAFcJeknRT/MN9p+5uLXKYTXq+HwUREv/W6BhgR/ZYAGBG9lQAYEb2VABgRvZUAGBG9lQAYEb2VABgRvfV/SxpEpjyVLI4AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a395179a260844ddb494322956f5fc09",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/10 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "making done, saving to  ../data/toy2c/val_data.npy\n",
      "done\n",
      "2\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "582a852f4a5f44a3bd29d26e72b1b2b4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/10 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "making done, saving to  ../data/toy2c/test_data.npy\n",
      "done\n"
     ]
    }
   ],
   "source": [
    "n_train_points = 100\n",
    "n_val_points = 10\n",
    "n_test_points = 10\n",
    "n_time_steps = 500\n",
    "dim = 4\n",
    "width_small = 2#int(dim/2)\n",
    "\n",
    "# params\n",
    "w0 = 0.5\n",
    "w1 = 1.0\n",
    "# width_small = 8\n",
    "num_periods_big = 8\n",
    "\n",
    "\n",
    "# paths\n",
    "data_dir = '../data/toy2c'\n",
    "result_dir = '../result/toy2c'\n",
    "\n",
    "\n",
    "x = np.arange(dim)\n",
    "y = np.arange(dim)\n",
    "train_data = make_data(n_train_points, 'train_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "print(train_data.shape)\n",
    "plt.imshow(train_data[0,0])\n",
    "plt.colorbar()\n",
    "plt.show()\n",
    "val_data = make_data(n_val_points, 'val_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "test_data = make_data(n_test_points, 'test_data.npy', data_dir=data_dir,width_small=width_small,dim=dim) \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(100, 500, 4, 4)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.colorbar.Colorbar at 0x7f342727fa60>"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAATkAAAD8CAYAAAAMs9NCAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAXTUlEQVR4nO3dcYxdZ33m8e+TwQkEkoasgZgkJBF16boVCXTqgOi2IZDieKlcdqOt0xXppiAriCBYtSsiVkpV9Y+C0KItTcAdgRUiIbJIBHCpgzeLYJNsSbCTdUwcE9ZrKvAmquUEYkyo7Zl59o9zxnu5e2fuGZ935t45fj7RUc695/X7vleRf3nP+573/GSbiIiuOmvUHYiIWEoJchHRaQlyEdFpCXIR0WkJchHRaQlyEdFpL2rzhyVdCPwX4HLgH4B/Y/vHA8r9A/BTYAaYtj3Zpt2IiKbajuRuA75hey3wjfrzfN5q+6oEuIhYTm2D3Cbgc/X554Dfb1lfRERRarPjQdJPbF/Q8/nHtl8+oNwPgB8DBv7G9tQCdW4BtgBMMPEb53L+afdvXP3K618YdRdikb6/99xRd2FJ/BM/44SPq00d73jrS/3sczONyj669/hO2xvmuy5pA/BXwATwGdsf7bv+cmAb8Frgn4A/tv3EQm0OnZOT9N+AiwZc+o/D/myPt9h+WtIrgfslfc/2A4MK1gFwCuB8Xeir9bZFNLMy7Ny5Z9RdiEV6x6uvGnUXlsQj/kbrOo48N8MjOy9pVHbVmv+9er5rkiaAO4HrgEPALknbbT/ZU+wjwB7b75L0q3X5BYPE0CBn++0LdOofJa2x/YykNcDheep4uv73YUlfBtYDA4NcRKw0ZsazJSpaDxywfRBA0j1UU2K9QW4d8JcAtr8n6XJJr7L9j/NV2nZObjvwR/X5HwFf7S8g6aWSzps7B34XWHB4GRErh4FZ3OgY4mLgRz2fD9Xf9Xoc+FcAktYDlwELDiPbBrmPAtdJ+l9UQ8yP1o2/WtKOusyrgIckPQ58B/g7219v2W5EjJHZhv8AqyXt7jm29FQzaG6wPzJ+FHi5pD3AB4D/CUwv1LdWz8nZfpYB98P17enG+vwgcGWbdiJifBlzsvnt6pEFHiM7BFza8/kS4OlfaMs+CtwMIEnAD+pjXtnxEBGtGJjBjY4hdgFrJV0h6WxgM9WU2CmSLqivAbwXeKAOfPNqNZKLiACazLcNZXta0q3ATqpHSLbZ3ifplvr6VuCfA3dLmqFakHjPsHoT5CKiFQMzhd4wbnsHsKPvu609598G1i6mzgS5iGityAMkSyRBLiJacbP5tpFJkIuIVmw4Ob4xLkEuItoSMwMfcRsPCXIR0YqB2YzkIqLLMpKLiM6qHgZOkIuIjjJw0uO7eSpBLiJaMWJmjHeIJshFRGuzzu1qRHRU5uQiouPETObkIqKrqjcDJ8hFREfZ4oQnRt2NeSXIRURrs2M8J1dkjClpg6SnJB2QdNuA65L0yfr6XklvLNFuRIxetfBwVqNjFFqP5BrmSrye6kV3a4GrgU/X/46IFW+8Fx5K9OxUrkTbJ4C5XIm9NgF3u/IwcEGdpzUiVri5hYcmxyiUaLVJrsQmZSJihZqxGh2jUCLINcmV2KRMVVDaMpeT8STHW3cuIpaWESf9okbHMA3m939J0t9KelzSPkk3D6uzRJAbmiuxYRkAbE/ZnrQ9uYpzCnQvIpZSqYWHnvn964F1wI2S1vUVez/wpO0rgWuA/9STonCgEkFuaK7E+vNN9Srrm4DnbT9ToO2IGDHT7Fa1we1qk/l9A+fViaVfBjwHTC9UaevV1Ya5EncAG4EDwAvUGbAjohsWsaiwWtLuns9Ttqfq80Fz9/1PYdxBNWh6GjgP+APbCyYLK/IwcINciaYaZkZEx9gs5hGSI7Yn57nWZO7+HcAe4FrgtcD9kh60fXS+Bsf34ZaIWBGqhYeJRscQTebubwburR9HOwD8APjVhSpNkIuI1grteGgyv/9D4G0Akl4FvA44uFCl2bsaEa0YFXlpZsP5/b8A7pL0Xarb2w/bPrJQvQlyEdFaqX2pDeb3nwZ+dzF1JshFRCtV3tXxnflKkIuIlpTXn0dEd1UpCfPSzIjoKFu5XY2Ibhvn98klyEVEK9X75DInFxGdNd5vBk6Qi4hWqkdIMpKLiI6a27s6rhLkIqK1JJeOiM6qXrWU29WI6LDMyUVEZ1VvIcntakR0VLWtK0EuIjprvEdyRXrWIFfiNZKel7SnPm4v0W5EjIdZ1OgYhdYjuZ5ciddRvaN9l6Tttp/sK/qg7Xe2bS8ixsuZsLp6KlcigKS5XIn9QS4iOqrrt6uDciVePKDcmyU9Luk+Sb82X2WStkjaLWn3SY4X6F5ELKW5HA9NjmEaTH39h55pryckzUi6cKE6S4zkmuRKfAy4zPYxSRuBrwBrB1VWJ5qdAjhfF/bXExFjxsB0gZFck6kv2x8HPl6X/z3g39t+bqF6S4zkhuZKtH3U9rH6fAewStLqAm1HxBiY9VmNjiFOTX3ZPgHMTX3N50bgC8MqLRHkhuZKlHSRJNXn6+t2ny3QdkSMWsNb1fp2dfXcdFR9bOmpqenUF5LOBTYAXxrWvda3qw1zJd4AvE/SNPBzYLPt3IpGdMAiX5p5xPbkPNeaTH3N+T3gfwy7VYVCDwM3yJV4B3BHibYiYvwU2rs6dOqrx2Ya3KpCoYeBI+LMNffSzAKrq0OnvgAk/RLwO8BXm/Qv27oiohUjpmfbj5caTn0BvAv4r7Z/1qTeBLmIaK3Ulq1hU1/157uAu5rWmSAXEe0475OLiA5LIpuI6LwEuYjoLCNmCiw8LJUEuYhobVTvimsiQS4iWnEWHiKi65wgFxHd1exdcaOSIBcRrWUkFxGdZcPMbIJcRHRYVlcjorNMblcjotOy8BARHTfO7/lOkIuI1sb5drXIhjNJ2yQdlvTEPNcl6ZN1LsW9kt5Yot2IGL1qdfWsRscolGr1LqrMOfO5nirP6lpgC/DpQu1GxBiwmx2jUCTI2X4AWChrzibgblceBi6QtKZE2xExerYaHaOwXOPHxeRT3DKXk/Ekx5elcxFx+kyzANckyEnaIOmpemrrtnnKXCNpj6R9kv77sDqXa+GhcT5F21PAFMD5unCM12wiYk6Jv6iSJoA7geuoBkK7JG23/WRPmQuATwEbbP9Q0iuH1btcI7nF5FOMiJXE4Fk1OoZYDxywfdD2CeAeqqmuXn8I3Gv7hwC2Dw+rdLmC3HbgpnqV9U3A87afWaa2I2KJFbpdbTKt9SvAyyV9S9Kjkm4aVmmR21VJXwCuAVZLOgT8GbAKTqUT2wFsBA4ALwA3l2g3IsbDIlZOV0va3fN5qp6igmbTWi8CfgN4G/AS4NuSHrb9/fkaLBLkbN845LqB95doKyLGyyL3rh6xPTnPtSbTWofqOn4G/EzSA8CVwLxBbnyzT0TEymDAanYsbBewVtIVks4GNlNNdfX6KvAvJL1I0rnA1cD+hSrNtq6IaK3Eg762pyXdCuwEJoBttvdJuqW+vtX2fklfB/YCs8BnbA/caTUnQS4iWmq0ctqI7R1Uc/i9323t+/xx4ONN60yQi4j2xviJ1gS5iGjH4/0WkgS5iGgvI7mI6LaM5CKiy2ZH3YH5JchFRDtzz8mNqQS5iGgtOR4iotsS5CKi03K7GhFdpozkIqKzLCi0rWspJMhFRHsZyUVEpyXIRUSnJchFRGeN+cPARd4MLGmbpMOSBr68rs6T+HydK3GPpNtLtBsR40FudoxCqZHcXcAdwN0LlHnQ9jsLtRcR46Trt6u2H5B0eYm6ImLlyXNylTdLepwq+86f2t43qJCkLcAWgBdz7jJ2b/m849VXjboLEWV1fU6ugceAy2xfCfw18JX5Ctqesj1pe3IV5yxT9yLitHkRxxCSNkh6StIBSbcNuL7o+f1lGcnZPtpzvkPSpySttn1kOdqPiCVW4HZV0gRwJ3AdVX7VXZK2236yr+ii5veXZSQn6SJJqs/X1+0+uxxtR8TS02yzY4j1wAHbB22fAO4BNrXtW5GRnKQvANcAqyUdAv4MWAWn0ondALxP0jTwc2CzPc5voIqIRWn+t3m1pN09n6dsT9XnFwM/6rl2iCp5dL9G8/tzSq2u3jjk+h1Uj5hERMcs8hm4I7Yn56tqwHf9Nc/N7x+TtJFqfn/tQg0u18JDRHSZ1exY2CHg0p7Pl1CN1v5fM/ZR28fq8x3AKkmrF6o0QS4i2iuzuroLWCvpCklnA5uB7b0FTmd+P3tXI6K1Eg8D256WdCuwE5gAttneJ+mW+vppze8nyEVEO260ctqsquoWdEffd1t7zhc9v58gFxHtjfGzEglyEdFeglxEdNk4b9DP6mpEdFpGchHR3hiP5BLkIqKdgqurSyFBLiLay0guIrpKjPfCQ4JcRLSXIBcRnTXCTFxNJMhFRHtZeIiILstILiK6LUEuIjqrYSauUWm9rUvSpZK+KWm/pH2SPjigjCR9sk4ztlfSG9u2GxHjY+4V6MOOUSgxkpsG/sT2Y5LOAx6VdH9fGrHrqd7DvpYqMcWnGZygIiJWoi6P5Gw/Y/ux+vynwH6qrDu9NgF3u/IwcIGkNW3bjojxUCgl4ZIo+hYSSZcDbwAe6bs0KNVYfyCcq2OLpN2Sdp/keMnuRcRSaJrfYUSjvWJBTtLLgC8BH7J9tP/ygD8y8CfbnrI9aXtyFeeU6l5ELBEt4hhal7RB0lP1/P1tC5T7TUkzkm4YVmeRICdpFVWA+7ztewcUGZpqLCJWsAIjOUkTwJ1Uc/jrgBslrZun3MeoEt4MVWJ1VcBngf22PzFPse3ATfUq65uA520/07btiBgPhVZX1wMHbB+0fQK4h2o+v98HqAZVh5v0rcTq6luAdwPflbSn/u4jwGvgVKadHcBG4ADwAnBzgXYjYlw0n29bLWl3z+cp21P1+aC5+194CkPSxcC7gGuB32zSYOsgZ/shhtxu13kR39+2rYgYQ4t7aeYR25PzXGsyd/+fgQ/bnqlzTA+VHQ8R0V6ZldMmc/eTwD11gFsNbJQ0bfsr81WaIBcRrRXazbALWCvpCuD/AJuBP+wtYPuKU21KdwFfWyjAQYJcRJRQIMjZnpZ0K9Wq6QSwzfY+SbfU17eeTr0JchHRWql9qbZ3UC1U9n43MLjZ/ndN6kyQi4h2TF6aGRHdlUQ2EdF9CXIR0WXy+Ea5BLmIaGfM3wycIBcRrWVOLiI6bVQvxGwiQS4i2stILiI6a4RJappIkIuI9hLkIqKr8jBwRHSeZsc3yiXIRUQ7eU4uIrpunB8hKZHI5lJJ35S0X9I+SR8cUOYaSc9L2lMft7dtNyLGyBjnXS0xkpsG/sT2Y5LOAx6VdL/tJ/vKPWj7nQXai4gx0+mFhzq14DP1+U8l7afKutMf5CKiiwyM8Qb9Isml50i6HHgD8MiAy2+W9Lik+yT92gJ1bJG0W9Lukxwv2b2IWCKabXaMQrEgJ+llVAlfP2T7aN/lx4DLbF8J/DXwlfnqsT1le9L25CrOKdW9iFgic8/JFUgujaQNkp6SdEDSbQOub5K0t57b3y3pt4bVWSTISVpFFeA+b/ve/uu2j9o+Vp/vAFZJWl2i7YgYMbv5sQBJE8CdwPXAOuBGSev6in0DuNL2VcAfA58Z1r0Sq6sCPgvst/2JecpcVJdD0vq63Wfbth0R46HQSG49cMD2QdsngHuATb0FbB+rk9UDvJQGa7YlVlffArwb+K6kPfV3HwFeU3dqK3AD8D5J08DPgc09HY2Ila753+bVknb3fJ6yPVWfXwz8qOfaIeDq/gokvQv4S+CVwL8c1mCJ1dWHqG7LFypzB3BH27YiYjwt4hGSI7Yn56tmwHf/X822vwx8WdJvA38BvH2hBrPjISLaMTBT5MbsEHBpz+dLgKfnbdZ+QNJrJa22fWS+ckUfIYmIM1OhObldwFpJV0g6G9gMbP+FdqRf7pnffyNwNkPm9zOSi4j2Ckyx256WdCuwE5gAttneJ+mW+vpW4F8DN0k6STW//wfD5vcT5CKitVLbuupHzHb0fbe15/xjwMcWU2eCXES0k1ctRUSXCVCZhYclkSAXEa1pjB97TZCLiHZyuxoR3TZ8X+ooJchFRGudfmlmRERGchHRXc7qakR03fjGuAS5iGgvj5BERLclyEVEZxkY4+TSCXIR0YpwblcjouNmx3coVyKRzYslfafOqbpP0p8PKCNJn6zTjO2tX3YXEV0wd7va5BiBEiO548C1to/VqQkfknSf7Yd7ylwPrK2Pq4FPMyBBRUSsTON8u9p6JOfKsfrjqvro/8WbgLvrsg8DF0ha07btiBgTBfKuLpVSyaUn6nSEh4H7bT/SV2RQqrGLS7QdEaNWJrn0UikS5GzP1BmtLwHWS/r1viKNUo0BSNoiabek3Sc5XqJ7EbGU5rJ1NTlGoGi2Lts/Ab4FbOi71DjVmO0p25O2J1dxTsnuRcQSkd3oGFqPtEHSU/Ui5W0Drv/bevFyr6S/l3TlsDpLrK6+QtIF9flLqBK9fq+v2HaqDDuS9CbgedvPtG07IsZEgdtVSRPAnVQLleuAGyWt6yv2A+B3bL+eKrH01LCulVhdXQN8ru7gWcAXbX+tL43YDmAjcAB4Abi5QLsRMQ4MzBa5FV0PHLB9EEDSPVSLlk+easr++57yD1PdFS6odZCzvRd4w4Dve9OIGXh/27YiYhwtalFhtaTdPZ+nbM+NxgYtUC70qNl7gPuGNZgdDxHRXvMgd8T25DzXFrNA+VaqIPdbwxpMkIuIdgzMFNnO0GiBUtLrgc8A19t+dlilRVdXI+JMZPBss2Nhu4C1kq6QdDawmWrR8hRJrwHuBd5t+/tNepeRXES0V+BBX9vTkm4FdgITwDbb+/oWMW8H/hnwKUkA0wvc/gIJchHRVrnVVWzvoHoao/e73kXM9wLvXUydCXIR0d4Yb9BPkIuI9hLkIqKzbJiZGXUv5pUgFxHtZSQXEZ2WIBcR3eViq6tLIUEuItoxePiDviOTIBcR7ZXZ1rUkEuQioh17rFMSJshFRHtZeIiILnNGchHRXaPLxNVEglxEtFNwg/5SSJCLiFYMeIy3dZXI1vViSd+R9LikfZL+fECZayQ9L2lPfdzett2IGBMu9tLMJVFiJHccuNb2MUmrgIck3Wf74b5yD9p+Z4H2ImLMuMu3q3UmrmP1x1X1Mb6/OCLKG+MdD3KBVZE65+qjwC8Dd9r+cN/1a4AvUSWqeBr4U9v75qlrC7Cl/vg64KnWHWxmNXBkmdpaTvldK89y/rbLbL+iTQWSvk7V5yaO2N7Qpr3FKhLkTlUmXQB8GfiA7Sd6vj8fmK1vaTcCf2V7bbGGC5C0e9i74lei/K6Vp8u/bRSKZuuy/RPgW8CGvu+P2j5Wn+8AVklqGvkjIk5bidXVV9QjOCS9BHg78L2+MhepTq0jaX3d7tB8iRERbZVYXV0DfK6elzsL+KLtr/WlEbsBeJ+kaeDnwGaXvE8uY2rUHVgi+V0rT5d/27IrOicXETFuis7JRUSMmwS5iOi0Mz7ISdog6SlJByTdNur+lCJpm6TDkp4YXnrlkHSppG9K2l9vI/zgqPtUQpPtkXF6zug5uXqx5PvAdVQPKu8CbrT95Eg7VoCk36baiXK37V8fdX9KkbQGWGP7MUnnUT2E/vsr/b9Z/fTBS3u3RwIfHLA9MhbpTB/JrQcO2D5o+wRwD7BpxH0qwvYDwHOj7kdptp+x/Vh9/lNgP3DxaHvVnivZHrkEzvQgdzHwo57Ph+jAX5gzhaTLgTcAj4y4K0VImpC0BzgM3G+7E79r1M70IKcB3+X/niuApJdR7Yf+kO2jo+5PCbZnbF8FXAKsl9SZaYZROtOD3CHg0p7Pl1C9QCDGWD1n9SXg87bvHXV/Sptve2ScnjM9yO0C1kq6QtLZwGZg+4j7FAuoJ+g/C+y3/YlR96eUJtsj4/Sc0UHO9jRwK7CTagL7i/O9AmqlkfQF4NvA6yQdkvSeUfepkLcA7wau7XnT9MZRd6qANcA3Je2l+p/v/ba/NuI+dcIZ/QhJRHTfGT2Si4juS5CLiE5LkIuITkuQi4hOS5CLiE5LkIuITkuQi4hO+7+IS0GRZCr41QAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "print(train_data.shape)\n",
    "plt.imshow(train_data[2,0])\n",
    "plt.colorbar()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def animate(snapshots, normalize = True, file_name = \"animation.gif\"):\n",
    "    \"\"\"\n",
    "    Makes an animation of snapshots in time\n",
    "    \n",
    "    inputs:\n",
    "    snapshots: np.array of size (n_time_steps,1, dim, dim)\n",
    "    normalize = True: whether to fix axis between 0 and 1 or not\n",
    "    file_name = \"animation.gif\": file name of where to save gif\n",
    "    \n",
    "    outputs:\n",
    "    no returned output\n",
    "    gif saved to file_name\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "    fps = 30\n",
    "    nSeconds = len(snapshots)/fps\n",
    "    \n",
    "    # First set up the figure, the axis, and the plot element we want to animate\n",
    "    fig = plt.figure( figsize=(8,8) )\n",
    "\n",
    "    a = snapshots[0,:,:,:][0].T\n",
    "    if normalize:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=0.0, vmax=1.0)\n",
    "    else:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=np.min(snapshots), vmax=np.max(snapshots))\n",
    "    plt.colorbar()\n",
    "\n",
    "    print(\"Animating, may take a little while...\")\n",
    "\n",
    "    def animate_func(i):\n",
    "        if i % fps == 0:\n",
    "            print( '.', end ='' )\n",
    "\n",
    "        im.set_array(snapshots[i,:,:,:,][0].T)\n",
    "        return [im]\n",
    "\n",
    "    anim = animation.FuncAnimation(\n",
    "                                   fig,\n",
    "                                   animate_func,\n",
    "                                   frames = int(nSeconds * fps),\n",
    "                                   interval = 1000 / fps, # in ms\n",
    "                                   )\n",
    "    writergif = animation.PillowWriter(fps=30)\n",
    "    anim.save(file_name, writer=writergif)\n",
    "\n",
    "    print('Done! gif saved to ', file_name)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Animating, may take a little while...\n",
      ".."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Error in callback <function flush_figures at 0x000001E2C30F44C0> (for post_execute):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2877, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2928, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\events.py\", line 89, in trigger\n",
      "    func(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 121, in flush_figures\n",
      "    return show(True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 41, in show\n",
      "    display(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\display.py\", line 313, in display\n",
      "    format_dict, md_dict = format(obj, include=include, exclude=exclude)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-2>\", line 2, in __call__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 341, in __call__\n",
      "    return printer(obj)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 248, in <lambda>\n",
      "    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 132, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2195, in print_figure\n",
      "    bbox_inches = self.figure.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 2506, in get_tightbbox\n",
      "    bbox = a.get_tightbbox(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 4155, in get_tightbbox\n",
      "    bb_xaxis = self.xaxis.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\numpy\\core\\_methods.py\", line 43, in _amin\n",
      "    return umr_minimum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
