{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# toy problem 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Generate data\n",
    "\n",
    "train_data size (100,500,128,128)\n",
    "\n",
    "validation size (10,500,128,128)\n",
    "\n",
    "test size (10,500,128,128)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# import sys\n",
    "import numpy as np\n",
    "# import scipy as sp\n",
    "# from scipy import integrate\n",
    "from tqdm.notebook import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.animation as animation\n",
    "# import torch\n",
    "\n",
    "# module_path = os.path.abspath(os.path.join('../src/'))\n",
    "# if module_path not in sys.path:\n",
    "#     sys.path.append(module_path)\n",
    "    \n",
    "    \n",
    "# import utils"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_data(n_points, file_name, data_dir = './data/toy2', n_time_steps = 500, dim = 128, num_periods_big = 8, w0=0.5, w1=1.0, width_small = 64):\n",
    "    \"\"\"\n",
    "    Makes data for toy2a\n",
    "    \n",
    "    Inputs:\n",
    "    n_points: int, how many data points \n",
    "    file_name: str, name of file to save\n",
    "    data_dir = './data/toy2': str, directory of where to store\n",
    "    n_time_steps = 500: int, how many time steps per data point\n",
    "    dim = 128: int, how many data points per dim, while be same in both x and y directions\n",
    "    num_periods_big = 8: int, how many periods of the slow scale\n",
    "    w0 = 0.5: float, frequency of slow scale\n",
    "    w1 = 1.0: float, frequency of fast scale\n",
    "    width_small = 8: width of small (fast) scale\n",
    "    \n",
    "    Output: \n",
    "    data: size (n_points,n_time_steps,dim, dim) will be returned and saved to file data_dir+file_name\n",
    "    \n",
    "    \"\"\"\n",
    "    print(width_small)\n",
    "    print(\"Making data\")\n",
    "    x = np.arange(dim)\n",
    "    y = np.arange(dim)\n",
    "    data = np.zeros((n_points, n_time_steps, dim, dim))\n",
    "\n",
    "    for i in tqdm(range(n_points)):\n",
    "        t_start = np.random.uniform(high=4*np.pi)\n",
    "        t = np.linspace(t_start, num_periods_big*4*np.pi + t_start, n_time_steps)\n",
    "\n",
    "\n",
    "        xgrid, ygrid, tgrid = np.meshgrid(x, y, t)\n",
    "\n",
    "        Phi = np.cos(w0*tgrid)\n",
    "\n",
    "        Phi[:width_small, :width_small,:] = np.cos(w1*tgrid[:width_small, :width_small,:]+np.pi/4)\n",
    "        scaled_Phi = (Phi.T - Phi.min()) / (Phi.max() - Phi.min())\n",
    "        data[i] = scaled_Phi\n",
    "\n",
    "    print(\"making done, saving to \", os.path.join(data_dir, file_name))\n",
    "    np.save(os.path.join(data_dir, file_name), data)\n",
    "    print(\"done\")\n",
    "    \n",
    "    return data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "dc91583d75d84ff3918f468e1acbcaeb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2a\\train_data.npy\n",
      "done\n",
      "(100, 500, 8, 8)\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAS4AAAD4CAYAAABSUAvFAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAATwUlEQVR4nO3db6xdVZ3G8e/DpcCAECNFxbYMqARCJhTIDY6BYEDRMhKrcRJhFDMq6fAClcwYg/PCeeErkonRF2jTIM5MRMkM0qTRSiX+CTNBsS02xQJlOpVJr9UpBQ3qOLS995kXZ1883J727NO7z5919/NJdnr2n7X374b4c621115LtomIKMlJ4w4gImJQSVwRUZwkrogoThJXRBQniSsiinPyMG66/DVTPn/VsmHcOobkmZ2njzuEGMD/8XsO+SUt5h7vuvYMP//CbK1rt+98aYvtNYt5XpOGkrjOX7WMn2xZNYxbx5C86w2XjTuEGMBj/t6i7/H8C7P8ZMt5ta6dOvc/ly/6gQ0aSuKKiMlnYI65cYdxQpK4IlrKmMOu11ScNElcES2WGldEFMWY2UI/+UviimixOZK4IqIgBmaTuCKiNKlxRURRDBxOH1dElMS42KZirW8VJa2RtFvSHkl3DjuoiBgBw2zNbdL0TVySpoC7gRuAS4CbJV0y7MAiYrg6I+frbZOmTo3rSmCP7b22DwH3A2uHG1ZEDJ+YrblNmjp9XCuAfV37M8BbFl4kaR2wDuC8Fek6i5h0nc75yUtKddSpcfX6y45q9dreYHva9vQ5Z08tPrKIGKrOOK6lW+OaAbrnqFkJ7B9OOBExSnOF1rjqJK6twIWSLgB+AdwE/NVQo4qIoZuvcZWob+KyfUTS7cAWYAq41/auoUcWEUNlxGyhs7fX6kW3vRnYPORYImLElnJTMSKWICMOucwXaUlcES3VGYC6hJuKEbE0LdnO+YhYmmwx69S4IqIwc6lxRURJOp3zZaaAMqOOiEVL53xEFGk247gioiQlj5wvM+qIaMScT6q19dNvlmRJayXtlLRD0jZJV3ede1bSE/Pn6sSdGldES3U+sl583aVrluTr6cwms1XSJttPdl32PWCTbUu6FPhX4OKu89faPlj3mUlcES1lxOFmPvl5eZZkAEnzsyS/nLhs/67r+jPoMaffINJUjGgpG2Z9Uq0NWF418ea3dV236jVL8oqFz5P0PklPA98GPtodCvBdSdsX3PeYUuOKaC0NMgD1oO3pY97oaL1mSd4IbJR0DfA54B3Vqats75f0WuBhSU/bfuR4waTGFdFSZqAa1/EMNEtylZTeJGl5tb+/+vcAsJFO0/O4krgiWmyWk2ptfbw8S7KkU+jMkryp+wJJb5ak6vcVwCnA85LOkHRmdfwM4J3Az/o9ME3FiJYyamQiwWPNkizptur8euD9wIclHQb+AHygesP4OjrNR+jko6/bfqjfM5O4IlqqszxZMymg1yzJVcKa/30XcFePcnuB1YM+r85K1vdKOiCpb/UtIkpS7oKwdfq4/glYM+Q4ImLETHMj50etzio/j0g6fwSxRMSITWJtqo7G+riqgWPrAM5bka6ziElnayJrU3U0lmFsbwA2AEyvPm1Rw/kjYvg6nfNZ5SciipI55yOiMJ3O+TL7uOoMh/gG8CPgIkkzkj42/LAiYhQaGjk/cnXeKt48ikAiYrSaGjk/DmkqRrRYFsuIiKLYcHguiSsiCtJpKiZxRURhWj9yPiLKUvJwiCSuiNZKUzEiCjTAnPMTJYkroqU6bxXzrWJEFCQDUCOiSGkqRkRR8lYxIoqUt4oRURRbHEniiojSlNpULDPdRsSizfdx1dn6kbRG0m5JeyTd2eP8Wkk7Je2QtE3S1XXL9pIaV0SLNVHjkjQF3A1cD8wAWyVtsv1k12XfAzZVq1dfCvwrcHHNskdJjSuipebHcTVQ47oS2GN7r+1DwP3A2lc8y/6d7flFdM6gU+GrVbaXJK6IFptDtTZgedXEm9/Wdd1mBbCva3+mOvYKkt4n6Wng28BHBym7UN+moqRVwL8ArwfmgA22v9ivXERMNhuO1J9I8KDt6WOc61UlO2qJQtsbgY2SrgE+B7yjbtmF6vRxHQH+zvbjks4Etkt6uF8bNCImX0NvFWeAVV37K4H9x7rY9iOS3iRp+aBl5/VNt7Z/afvx6vdvgaeoUZWLiMnWYB/XVuBCSRdIOgW4CdjUfYGkN0tS9fsK4BTg+TplexnoraKk84HLgcd6nFsHrAM4b0VeVkaUwA3UuGwfkXQ7sAWYAu61vUvSbdX59cD7gQ9LOgz8AfhA1Vnfs2y/Z9bOMJJeBXwTuMP2iz2C3wBsAJhefVrfNmpEjF9TH1nb3gxsXnBsfdfvu4C76pbtp1bikrSMTtK6z/aDgzwgIiaTXe7I+TpvFQV8BXjK9ueHH1JEjIaYLXR5sjpRXwXcAlxXDdffIekvhhxXRIyArVrbpOlb47L9H/QeaxERBct8XBFRHnf6uUqUxBXRYpm6OSKK4oI755O4IlosTcWIKM4kvjGsI4kroqXsJK6IKFCGQ0REcdLHFRFFMWIubxUjojSFVriSuCJaK53zEVGkQqtcSVwRLZYaV0QUxcDcXBJXRJTEQGpcEVGajOOKiPIkcUVEWSZzWuY66iyWcRrwCHBqdf0Dtv9h2IFFxAgUWuOqM97/JeA626uBy4A1kv58qFFFxPAZPKdaWz+S1kjaLWmPpDt7nP+gpJ3V9qik1V3nnpX0RLUQz7Y6oddZLMPA76rdZdVWaJ6OiFdafFNR0hRwN3A9MANslbTJ9pNdl/0ceJvtX0u6gc7i0W/pOn+t7YN1n1nrC0tJU5J2AAeAh20/1uOadZK2Sdr23POzdZ8fEePkmtvxXQnssb3X9iHgfmDtKx5jP2r719Xuj4GViwm7VuKyPWv7suphV0r6sx7XbLA9bXv6nLOnFhNTRIxK/cS1fL5iUm3ruu6yAtjXtT9THTuWjwHfWRDFdyVtX3DfYxroraLt30j6IbAG+NkgZSNiwgw2APWg7eljnOt1k571NEnX0klcV3cdvsr2fkmvBR6W9LTtR44XTN8al6RzJL26+v0nwDuAp/uVi4jJZ9fb+pgBVnXtrwT2L7xI0qXAPcBa28//MQbvr/49AGyk0/Q8rjpNxXOBH0jaCWyl08f1rRrlImLSzanednxbgQslXSDpFOAmYFP3BZLOAx4EbrH9TNfxMySdOf8beCc1WnN13iruBC7vd11ElEcNjA+wfUTS7cAWYAq41/YuSbdV59cDnwXOBr4kCeBI1fR8HbCxOnYy8HXbD/V7ZkbOR7RVvTeG9W5lbwY2Lzi2vuv3rcCtPcrtBVYvPN5PEldEaymzQ0REgQodSp7EFdFmc+MO4MQkcUW0VSYSjIgSNfFWcRySuCLarNDEVeYythHRakOpcT2z83Te9YbLhnHriGhQmooRURZT53OeiZTEFdFmqXFFRGnSVIyI8iRxRURxkrgioiRymooRUaK8VYyI0qTGFRHlSeKKiKIU3MdV+1vFalHYn0rKQhkRS0UzC8KO3CA1rk8CTwFnDSmWiBgxFTqRYK0al6SVwLvprIkWETFWdZuKXwA+zXEmepW0bn557sO81ERsETFshTYV66xkfSNwwPb2411ne4PtadvTyzi1sQAjYkj8x0Go/bZJU6fGdRXwHknPAvcD10n62lCjiojRaKjGJWmNpN2S9ki6s8f5D0raWW2PSlpdt2wvfROX7c/YXmn7fDpLa3/f9ofq3DwiJlwDiUvSFHA3cANwCXCzpEsWXPZz4G22LwU+B2wYoOxRMnVzREuJzlvFOlsfVwJ7bO+1fYhOy2xt9wW2H7X962r3x8DKumV7GShx2f6h7RsHKRMRE2qwPq7l8y/fqm1d151WAPu69meqY8fyMeA7J1gWyMj5iHar3/F+0Pb0Mc71+lK7550lXUsncV09aNluSVwRbdbMG8MZYFXX/kpg/8KLJF1KZyzoDbafH6TsQunjimixhoZDbAUulHSBpFPovMTb9IrnSOcBDwK32H5mkLK9pMYV0WYN1LhsH5F0O7AFmALutb1L0m3V+fXAZ4GzgS9JAjhSjfvsWbbfM5O4ItrKzX2raHszsHnBsfVdv28Fbq1btp8krog2m8BR8XUkcUW02CR+zlNHEldEmyVxRURRJnTmhzqSuCJaSqSpGBEFSuKKiPIkcUVEcZK4IqIoEzq7aR1JXBFtlsQVEaUpdXmyJK6IFktTMSLKstQHoFYr/PwWmKWajmKYQUXEiCzlxFW51vbBoUUSESOVkfMRUSTNlZm56k7dbOC7krYvWN3jZZLWza8AcpiXmoswIoaj7pqKE5jb6ta4rrK9X9JrgYclPW37ke4LbG+gWuTxLL1mAv/UiFio1KZirRqX7f3VvweAjXQWcYyI0hVa4+qbuCSdIenM+d/AO4GfDTuwiBi+hlb5Gbk6TcXXARurlTlOBr5u+6GhRhURozGBSamOvonL9l5g9QhiiYhRanCVn1HLcIiIlip5HFdWso5oM7ve1oekNZJ2S9oj6c4e5y+W9CNJL0n61IJzz0p6QtIOSdvqhJ0aV0SLNVHjkjQF3A1cD8wAWyVtsv1k12UvAJ8A3nuM2wz0ZU5qXBFt1dwA1CuBPbb32j4E3A+sfcWj7AO2twKHmwg9iSuixTRXbwOWz38ZU23dX9CsAPZ17c9Ux+rq+2XOQmkqRrTYAG8VDx5nVhj1ODZII7TvlzkLpcYV0Vamqc75GWBV1/5KYH/tME7gy5wkrogWa2jk/FbgQkkXSDoFuAnYVOv5J/hlTpqKEW3WwFtF20ck3Q5sAaaAe23vknRbdX69pNcD24CzgDlJdwCXAMs5gS9zkrgiWqrJAai2NwObFxxb3/X7V3SakAu9yAl8mZPEFdFWdrETCSZxRbRZmXkriSuizUr9VjGJK6KtDKSpGBHFKTNvJXFFtFmaihFRnLxVjIiyTOhCGHXU+uRH0qslPSDpaUlPSXrrsAOLiOHqDEB1rW3S1K1xfRF4yPZfVt8inT7EmCJiVJbqnPOSzgKuAf4aoJoo7NBww4qIUZjE2lQddZqKbwSeA74q6aeS7qm+4n4FSevmJxk7zEuNBxoRDWtuBtSRq5O4TgauAL5s+3Lg98BRk+Hb3mB72vb0Mk5tOMyIaF7nW8U626Spk7hmgBnbj1X7D9BJZBFRuoZW+Rm1vomrmo5in6SLqkNvB548TpGIKIEHmnN+otR9q/hx4L7qjeJe4CPDCykiRmYCa1N11EpctncAx5ooPyJKVWbeysj5iDbT3AS2A2tI4opoK7N0B6BGxNIkJvNznjqSuCLaLIkrIoqTxBURRSm4jysrWUe0mObmam197yOtkbRb0h5JR30SKOliST+S9JKkTw1StpckrojWqvm5T5/mpKQp4G7gBjqrU98s6ZIFl70AfAL4xxMoe5Qkroi2Mk19q3glsMf23mraq/uBta94lH3A9lbg8KBle0niimizuZobLJ+ftqra1nXdZQWwr2t/pjpWxwmVTed8RIsNMI7roO1jffanHsfq3viEyiZxRbRZM8MhZoBVXfsrgf3DLJumYkRb2TA7V287vq3AhZIuqGaQuQnYVDOKEyqbGldEmzVQ47J9RNLtwBZgCrjX9i5Jt1Xn10t6PbANOAuYk3QHcIntF3uV7ffMJK6INmto5LztzcDmBcfWd/3+FZ1mYK2y/SRxRbSVgQmcT76OJK6I1jK4zG9+krgi2srU6XifSH3fKkq6SNKOru3FqmMtIkpX6Co/fWtctncDl8HL3xX9Atg43LAiYiQmMCnVMWhT8e3Af9n+72EEExGjNJm1qToGTVw3Ad/odaL6dmkdwGmcvsiwImLoDBS6WEbtkfPVqNb3AP/W67ztDbanbU8v49Sm4ouIYVqqfVxdbgAet/0/wwomIkbJxb5VHCRx3cwxmokRUSCDl/I4LkmnA9cDfzPccCJipJbyyHnb/wucPeRYImLUJrD/qo6MnI9oK7vYt4pJXBFtlhpXRJTFeHZ23EGckCSuiLbKtDYRUaSlPBwiIpYeA06NKyKK4kwkGBEFKrVzXh7C61BJzwGDTn2zHDjYeDCTYan+bfm7xudPbZ+zmBtIeojO31rHQdtrFvO8Jg0lcZ0ISduOs1Ju0Zbq35a/K8YlC8JGRHGSuCKiOJOUuDaMO4AhWqp/W/6uGIuJ6eOKiKhrkmpcERG1JHFFRHEmInFJWiNpt6Q9ku4cdzxNkLRK0g8kPSVpl6RPjjumJkmakvRTSd8adyxNkvRqSQ9Ierr6b/fWcccURxt7H1e1yOwzdKaGngG2AjfbfnKsgS2SpHOBc20/LulMYDvw3tL/rnmS/haYBs6yfeO442mKpH8G/t32PdXKVqfb/s2Yw4oFJqHGdSWwx/Ze24eA+4G1Y45p0Wz/0vbj1e/fAk8BK8YbVTMkrQTeDdwz7liaJOks4BrgKwC2DyVpTaZJSFwrgH1d+zMskf+Bz5N0PnA58NiYQ2nKF4BPA2V+oXtsbwSeA75aNYPvkXTGuIOKo01C4lKPY0tmjIakVwHfBO6w/eK441ksSTcCB2xvH3csQ3AycAXwZduXA78HlkSf61IzCYlrBljVtb8S2D+mWBolaRmdpHWf7QfHHU9DrgLeI+lZOs366yR9bbwhNWYGmLE9XzN+gE4iiwkzCYlrK3ChpAuqztCbgE1jjmnRJIlOX8lTtj8/7niaYvsztlfaPp/Of6vv2/7QmMNqhO1fAfskXVQdejuwJF6mLDVjn4/L9hFJtwNbgCngXtu7xhxWE64CbgGekLSjOvb3tjePL6So4ePAfdX/ie4FPjLmeKKHsQ+HiIgY1CQ0FSMiBpLEFRHFSeKKiOIkcUVEcZK4IqI4SVwRUZwkrogozv8D65J/CyioyfoAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "cda34ec6e5fa4949a924b44fade97836",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=10.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2a\\val_data.npy\n",
      "done\n",
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "145395f3e5f64dcab6f5f5489fd0b1ed",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=10.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2a\\test_data.npy\n",
      "done\n"
     ]
    }
   ],
   "source": [
    "n_train_points = 100\n",
    "n_val_points = 10\n",
    "n_test_points = 10\n",
    "n_time_steps = 500\n",
    "dim = 8\n",
    "width_small = int(dim/2)\n",
    "\n",
    "# params\n",
    "w0 = 0.5\n",
    "w1 = 1.0\n",
    "# width_small = 8\n",
    "num_periods_big = 8\n",
    "\n",
    "\n",
    "# paths\n",
    "data_dir = './data/toy2a'\n",
    "result_dir = './result/toy2a'\n",
    "\n",
    "\n",
    "x = np.arange(dim)\n",
    "y = np.arange(dim)\n",
    "train_data = make_data(n_train_points, 'train_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "print(train_data.shape)\n",
    "plt.imshow(train_data[0,0])\n",
    "plt.colorbar()\n",
    "plt.show()\n",
    "val_data = make_data(n_val_points, 'val_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "test_data = make_data(n_test_points, 'test_data.npy', data_dir=data_dir,width_small=width_small,dim=dim) \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(100, 500, 8, 8)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.colorbar.Colorbar at 0x2042fe6a610>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAScAAAD4CAYAAACuRSAPAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAAT40lEQVR4nO3df6xfdX3H8eeLSxGLoNOiYlulug7DFgF3V2Nw/gCRomhnZmJhamSajmU1mi1T3B8umf/MmBhMRJumVlxkdA7Bda5SiQ7RqVhAREopu6vOXqqDwgzCHOXe+9of33PZt5d7v99z7Tnf7/ne83okJ3zPDz/nfUN4+/l8zueHbBMR0TTHDTuAiIj5JDlFRCMlOUVEIyU5RUQjJTlFRCMdX0ehK5495tNXL6uj6KjJfXctH3YIsQj/y2Mc8eM6ljIufN1Jfujh6VLP3n7X47ttrz+W9y1WLcnp9NXL+P7u1XUUHTW58AVnDzuEWIRb/fVjLuOhh6f5/u4Xlnp27LR/X3HML1ykWpJTRDSfgRlmhh3GgpKcIlrKmCdcrlk3DElOES2WmlNENI4x0w2evpbkFNFiMyQ5RUTDGJhOcoqIJkrNKSIax8AT6XOKiKYxbnSzrtTcOknrJe2XNCHpirqDiogBMEyXPIahb3KSNAZcBVwEnAlcIunMugOLiHp1RoiXO4ahTM1pHTBh+4DtI8AOYEO9YUVE/cR0yWMYyvQ5rQQOdp1PAq+Y+5CkTcAmgBeuTFdWRNN1OsSHk3jKKFNzmi/6p7RCbW+1PW57/NTnjB17ZBFRq844p9GuOU0C3eufrAIO1RNORAzSTINrTmWS0x5graQ1wP3ARuDSWqOKiNrN1pyaqm9ysj0laTOwGxgDttveW3tkEVErI6YbvFJ3qZ5r27uAXTXHEhEDNurNuohYgow44uZ+vEpyimipziDMEW/WRcTSNNId4hGxNNli2s2tOTU3soio3QwqdfTTb3EASc+U9M+Sfihpr6TL+pWZmlNES3U6xI89BXQtDnABnUHbeyTttH1P12N/Btxj+82STgX2S7qmmK87r9ScIlpqtkO8zNFHmcUBDJwsScAzgIeBqV6FpuYU0WLT5cc5rZB0W9f5Vttbi99lFgf4FLCTztS3k4G32+65GkuSU0RLLXKE+GHb4wvcK7M4wIXAncB5wEuAmyR9y/YjC70wzbqIFpvxcaWOPsosDnAZcL07JoAfAy/tVWiSU0RLdSb+Hlfq6OPJxQEknUBncYCdc575KXA+gKTnAWcAB3oVmmZdREsZ8UQF01cWWhxA0uXF/S3AR4GrJf2ITjPwQ7YP9yo3ySmipWwqG4Q53+IARVKa/X0IeMNiykxyimitcgMshyXJKaKlTHU1pzokOUW02MgvNhcRS49RFpuLiObpbA3V3BRQZsff7ZIekHT3IAKKiEFp9qaaZRqcVwPra44jIgbMVDZCvBZldl+5RdLpA4glIgasFSthZjvyiNFia2i1ojIqyyLF8glbAcbPOvEp25VHRLN0OsSz+0pENE6z1xBPcopoqU6HeHP7nMoMJbgW+C5whqRJSe+pP6yIGISKlkypRZmvdZcMIpCIGKyMEI+IxsqOvxHRODY8MZPkFBEN02nWJTlFRAO1YoR4RIyWkR9KEBFLlSqb+CtpvaT9kiYkXTHP/b+UdGdx3C1pWtKze5WZ5BTRYjPFOuL9jl4kjQFXARcBZwKXSDqz+xnbH7d9tu2zgQ8D37T9cK9y06yLaKnO17pK5tatAyZsHwCQtAPYANyzwPOXANf2KzQ1p4iWmh2EWeboYyVwsOt8srj2FJKW01kf7kv9Ck3NKaLFFrE11ApJt3Wdby1WIgHmLWShlUneDPxbvyYdJDlFtNYiv9Ydtj2+wL1JYHXX+Srg0ALPbqREkw6SnCJaraJBmHuAtZLWAPfTSUCXzn1I0jOB1wDvKFNoklNES9liqoLkZHtK0mZgNzAGbLe9V9Llxf3ZbcnfCnzN9mNlyk1yimixqgZh2t4F7Jpzbcuc86vpbJhSSpJTREs1fYR4klNEiyU5RUTjZLG5iGisRYxzGri+yUnSauDvgOcDM3QGX32y7sAiol42TI34YnNTwF/YvkPSycDtkm6yvdC8mYgYESPdrLP9M+Bnxe9fStpHZ95MklPECFtSfU6STgfOAW6d5162I48YMW5wcird4JT0DDoziT9g+5G5921vtT1ue/zU5zR3i+OI+H9VrOdUl1JVHEnL6CSma2xfX29IETEI9oj3OUkS8Flgn+1P1B9SRAyGmG7w17oykZ0LvBM4r2sN4DfWHFdEDICtUscwlPla923mX0wqIkZY5tZFRDO50+/UVElOES020tNXImJpcsM7xJOcIloszbqIaKQmjxBPcopoKTvJKSIaqslDCZrbGxYRtbPLHf1IWi9pv6QJSVcs8Mxri0HceyV9s1+ZqTlFtJQRMxV8rZM0BlwFXEBng809knZ2r/km6VnAp4H1tn8q6bn9yk3NKaLFXPLoYx0wYfuA7SPADmDDnGcuBa63/VMA2w/0KzTJKaKtvKi5dSsk3dZ1bOoqaSVwsOt8srjW7beA35B0s6TbJb2rX3hp1kW0WflxTodtjy9wb75e9bklHw/8LnA+8HTgu5K+Z/u+hV6Y5BTRYhUNJZgEVnedrwIOzfPM4WIr8sck3QKcBSyYnNKsi2gpAzMzKnX0sQdYK2mNpBOAjcDOOc/8E/D7ko6XtBx4BbCvV6GpOUW0lYEKak62pyRtBnYDY8B223slXV7c32J7n6QbgbvobDG3zfbdvcpNcoposarm1tneBeyac23LnPOPAx8vW2aSU0SbZeJvRDTP8JbgLaPMBgcnArcATyuev872X9cdWEQMwIjXnB4HzrP9aLFF1LclfdX292qOLSLqZHD/L3FDU2aDAwOPFqfLiqPB+TYiymtucio1zknSmKQ7gQeAm2zPux357ND2Bx+arjjMiKhFRZPr6lAqOdmetn02nZGf6yT9zjzPZDvyiFEz6slplu1fADcD6+sIJiIGaHYQZpljCPomJ0mnFmuxIOnpwOuBe2uOKyIGoKrF5upQ5mvdacDniwWljgO+aPsr9YYVEQMx4l/r7gLOGUAsETFgavB394wQj2irIXZ2l5HkFNFaw+vsLiPJKaLNUnOKiEaaGXYAC0tyimirihabq0uSU0SL5WtdRDRTg5NTNjiIiEaqpeZ0313LufAFZ9dRdERUqKpmnaT1wCfpbHCwzfbfzrn/Wjo7sPy4uHS97b/pVWaadRFtZSqZvlJMbbsKuIDO/nR7JO20fc+cR79l++Ky5aZZF9Fm1SyZsg6YsH3A9hFgB7DhWENLcopoMbncAayYXUyyODZ1FbMSONh1Pllcm+uVkn4o6auSfrtfbGnWRbRZ+T6nw7bHF7g3X9twbsl3AC8q9iJ4I/BlYG2vF6bmFNFm1TTrJoHVXeergENHvcZ+xPajxe9dwDJJK3oVmuQU0VJlm3QlvujtAdZKWiPpBGAjsPOod0nPl6Ti9zo6ueehXoWmWRfRZhV8rbM9JWkzsJvOUILttvdKury4vwV4G/CnkqaAXwEbi52dFpTkFNFiVY1zKppqu+Zc29L1+1PApxZTZpJTRJs1ePpKklNEW5XrTxqa0h3ixcaaP5CUzQ0ilooG71u3mJrT+4F9wCk1xRIRA6YGLzZXdjvyVcCbgG31hhMR0VG2WXcl8EF6LOopadPs0PYneLyK2CKibg1u1pXZ8fdi4AHbt/d6zvZW2+O2x5fxtMoCjIiaVDcIsxZl+pzOBd5SzIc5EThF0hdsv6Pe0CKidqP8tc72h22vsn06nWHp30hiilgiGtysyziniJYSzf5at6jkZPtm4OZaIomIwWr4IMzUnCLaLMkpIhopySkimijNuohopiSniGgcL6GvdRGxxKTmFBFNlD6niGimBien7L4S0VZlp66USGCS1kvaL2lC0hU9nvs9SdOS3tavzCSniJYS1axKIGkMuAq4CDgTuETSmQs89zE6u7T0leQU0WIVLZmyDpiwfcD2EWAHsGGe594HfAl4oExsSU4RbVa+WbdidjHJ4tjUVcpK4GDX+WRx7UmSVgJvBbZQUjrEI9qsfIf4YdvjC9ybb2fOuSVfCXzI9nSx8W9fSU4RbVXdqgSTwOqu81XAoTnPjAM7isS0AnijpCnbX16o0CSniDarJjntAdZKWgPcT2dRykuPeo29Zva3pKuBr/RKTJDkFNFqVUxfsT0laTOdr3BjwHbbeyVdXtwv3c/ULckposWqGiFuexewa861eZOS7XeXKTPJKaKthrg+eBmlkpOknwC/BKaBqR699hExSkY9ORVeZ/twbZFExEDNjhBvqjTrIlpMM83NTmVHiBv4mqTb54wMfVK2I48YMRVO/K1D2ZrTubYPSXoucJOke23f0v2A7a3AVoBT9OzmpuOIeFKTm3Wlak62DxX/fAC4gc5Ev4gYdQ2uOfVNTpJOknTy7G/gDcDddQcWEfWraFWCWpRp1j0PuKGYE3M88Pe2b6w1qogYjAY36/omJ9sHgLMGEEtEDFJ2X4mIJso4p4hoLjc3OyU5RbRYak4R0TxLYeJvRCxN6RCPiEZKcoqI5jHpEI+IZkqHeEQ0U4OTUzbVjGipqrYjB5C0XtJ+SROSrpjn/gZJd0m6s1ha6VX9ykzNKaKt7EoWm5M0BlwFXEBnD7s9knbavqfrsa8DO21b0suALwIv7VVuak4RbVbNkinrgAnbB2wfAXYAG456jf2o/WTv+0llSk1yimixRTTrVsyudFsc3SvirgQOdp1PFteOfpf0Vkn3Av8C/HG/2NKsi2grA+WbdYd77LqkBUo/+oJ9A53ll14NfBR4fa8XpuYU0WbVNOsmgdVd56uAQwu+srPE90skrehVaJJTRItV9LVuD7BW0hpJJwAbgZ1HvUf6TRUrVkp6OXAC8FCvQtOsi2ixKr7W2Z6StBnYDYwB223vlXR5cX8L8IfAuyQ9AfwKeHtXB/m8kpwi2qrCVQls7wJ2zbm2pev3x4CPLabMUs06Sc+SdJ2keyXtk/TKxbwkIpqnMwjTpY5hKFtz+iRwo+23FW3K5TXGFBGDMsqrEkg6BXg18G6AYpDVkXrDiohBGFatqIwyzboXAw8Cn5P0A0nbiv3rjpLtyCNGTMO3Iy+TnI4HXg58xvY5wGPAUyb22d5qe9z2+DKeVnGYEVG9zty6MscwlElOk8Ck7VuL8+voJKuIGHV2uWMI+iYn2z8HDko6o7h0PnBPj/9JRIyCYlPNMscwlP1a9z7gmuJL3QHgsvpCioiBaXCHeKnkZPtOYKFJfxExqpqbmzJCPKLNNNPcgU5JThFtZUZ7EGZELE1ieFNTykhyimizJKeIaKQkp4honPQ5RURT5WtdRDTQ8KamlJHkFNFWJskpIhqqua267L4S0WZVLdMrab2k/ZImJD1lSSVJfyTpruL4jqSz+pWZmlNEm1XQrJM0BlwFXEBniaU9knba7l695MfAa2z/t6SLgK3AK3qVm+QU0VY2TFfSrlsHTNg+ACBpB7CBrqWVbH+n6/nv0dl4s6c06yLarPxicytml+Eujk1dpawEDnadTxbXFvIe4Kv9QkvNKaLNyjfrDtteaNkkzVfyvA9Kr6OTnF7V74VJThFtZaCa9cEngdVd56uAQ3MfkvQyYBtwke2eW5FDmnURLWbwTLmjtz3AWklritVyNwI7ux+Q9ELgeuCdtu8rE11qThFtZSrpELc9JWkzsBsYA7bb3ivp8uL+FuAjwHOAT0sCmOrRTATKbap5BvAPXZdeDHzE9pW/zh8SEQ1S0Qhx27uAXXOuben6/V7gvYsps29ysr0fOBueHM9wP3DDYl4SEQ21hKavnA/8h+3/rCOYiBikpTXxdyNw7Xw3inEPmwBOZPkxhhURtTPQ4CVTSn+tK3rh3wL843z3sx15xAhq8I6/i6k5XQTcYfu/6gomIgapsukrtVhMcrqEBZp0ETGCDO4/hmloSiUnScvpzDj+k3rDiYiBqmaEeC3Kbkf+P3QGUEXEUrKEvtZFxFJhN/prXZJTRJul5hQRzWM8PT3sIBaU5BTRVtUtmVKLJKeINhv1oQQRsfQYcGpOEdE4dmpOEdFMTe4Ql2v4lCjpQWCxy6qsAA5XHkwzLNW/LX/X8LzI9qnHUoCkG+n8rWUctr3+WN63WLUkp1+HpNv6Lds5qpbq35a/K+qUDQ4iopGSnCKikZqUnLYOO4AaLdW/LX9X1KYxfU4REd2aVHOKiHhSklNENFIjkpOk9ZL2S5qQdMWw46mCpNWS/lXSPkl7Jb1/2DFVSdKYpB9I+sqwY6mSpGdJuk7SvcW/u1cOO6a2GnqfU7FR5310lgGepLPv+iW27xlqYMdI0mnAabbvkHQycDvwB6P+d82S9OfAOHCK7YuHHU9VJH0e+JbtbcWOQ8tt/2LIYbVSE2pO64AJ2wdsHwF2ABuGHNMxs/0z23cUv38J7ANWDjeqakhaBbwJ2DbsWKok6RTg1cBnAWwfSWIaniYkp5XAwa7zSZbIf8SzJJ0OnAPcOuRQqnIl8EGgubNGfz0vBh4EPlc0WbdJOmnYQbVVE5KT5rm2ZMY3SHoG8CXgA7YfGXY8x0rSxcADtm8fdiw1OB54OfAZ2+cAjwFLog90FDUhOU0Cq7vOVwGHhhRLpSQto5OYrrF9/bDjqci5wFsk/YROE/w8SV8YbkiVmQQmbc/WcK+jk6xiCJqQnPYAayWtKTogNwI7hxzTMZMkOn0X+2x/YtjxVMX2h22vsn06nX9X37D9jiGHVQnbPwcOSjqjuHQ+sCQ+YIyioa/nZHtK0mZgNzAGbLe9d8hhVeFc4J3AjyTdWVz7K9u7hhdSlPA+4Jri/ygPAJcNOZ7WGvpQgoiI+TShWRcR8RRJThHRSElOEdFISU4R0UhJThHRSElOEdFISU4R0Uj/BxD9M/fkWB0QAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "print(train_data.shape)\n",
    "plt.imshow(train_data[2,0])\n",
    "plt.colorbar()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def animate(snapshots, normalize = True, file_name = \"animation.gif\"):\n",
    "    \"\"\"\n",
    "    Makes an animation of snapshots in time\n",
    "    \n",
    "    inputs:\n",
    "    snapshots: np.array of size (n_time_steps,1, dim, dim)\n",
    "    normalize = True: whether to fix axis between 0 and 1 or not\n",
    "    file_name = \"animation.gif\": file name of where to save gif\n",
    "    \n",
    "    outputs:\n",
    "    no returned output\n",
    "    gif saved to file_name\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "    fps = 30\n",
    "    nSeconds = len(snapshots)/fps\n",
    "    \n",
    "    # First set up the figure, the axis, and the plot element we want to animate\n",
    "    fig = plt.figure( figsize=(8,8) )\n",
    "\n",
    "    a = snapshots[0,:,:,:][0].T\n",
    "    if normalize:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=0.0, vmax=1.0)\n",
    "    else:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=np.min(snapshots), vmax=np.max(snapshots))\n",
    "    plt.colorbar()\n",
    "\n",
    "    print(\"Animating, may take a little while...\")\n",
    "\n",
    "    def animate_func(i):\n",
    "        if i % fps == 0:\n",
    "            print( '.', end ='' )\n",
    "\n",
    "        im.set_array(snapshots[i,:,:,:,][0].T)\n",
    "        return [im]\n",
    "\n",
    "    anim = animation.FuncAnimation(\n",
    "                                   fig,\n",
    "                                   animate_func,\n",
    "                                   frames = int(nSeconds * fps),\n",
    "                                   interval = 1000 / fps, # in ms\n",
    "                                   )\n",
    "    writergif = animation.PillowWriter(fps=30)\n",
    "    anim.save(file_name, writer=writergif)\n",
    "\n",
    "    print('Done! gif saved to ', file_name)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Animating, may take a little while...\n",
      ".."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Error in callback <function flush_figures at 0x000001E2C30F44C0> (for post_execute):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2877, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2928, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\events.py\", line 89, in trigger\n",
      "    func(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 121, in flush_figures\n",
      "    return show(True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 41, in show\n",
      "    display(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\display.py\", line 313, in display\n",
      "    format_dict, md_dict = format(obj, include=include, exclude=exclude)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-2>\", line 2, in __call__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 341, in __call__\n",
      "    return printer(obj)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 248, in <lambda>\n",
      "    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 132, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2195, in print_figure\n",
      "    bbox_inches = self.figure.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 2506, in get_tightbbox\n",
      "    bbox = a.get_tightbbox(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 4155, in get_tightbbox\n",
      "    bb_xaxis = self.xaxis.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\numpy\\core\\_methods.py\", line 43, in _amin\n",
      "    return umr_minimum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
