{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# toy problem 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Generate data\n",
    "\n",
    "train_data size (100,500,128,128)\n",
    "\n",
    "validation size (10,500,128,128)\n",
    "\n",
    "test size (10,500,128,128)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "from tqdm.notebook import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.animation as animation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_data(n_points, file_name, data_dir = './data/toy2', n_time_steps = 500, dim = 128, num_periods_big = 8, w0=0.5, w1=1.0, width_small = 64):\n",
    "    \"\"\"\n",
    "    Makes data for toy2a\n",
    "    \n",
    "    Inputs:\n",
    "    n_points: int, how many data points \n",
    "    file_name: str, name of file to save\n",
    "    data_dir = './data/toy2': str, directory of where to store\n",
    "    n_time_steps = 500: int, how many time steps per data point\n",
    "    dim = 128: int, how many data points per dim, while be same in both x and y directions\n",
    "    num_periods_big = 8: int, how many periods of the slow scale\n",
    "    w0 = 0.5: float, frequency of slow scale\n",
    "    w1 = 1.0: float, frequency of fast scale\n",
    "    width_small = 8: width of small (fast) scale\n",
    "    \n",
    "    Output: \n",
    "    data: size (n_points,n_time_steps,dim, dim) will be returned and saved to file data_dir+file_name\n",
    "    \n",
    "    \"\"\"\n",
    "    print(width_small)\n",
    "    print(\"Making data\")\n",
    "    x = np.arange(dim)\n",
    "    y = np.arange(dim)\n",
    "    data = np.zeros((n_points, n_time_steps, dim, dim))\n",
    "\n",
    "    for i in tqdm(range(n_points)):\n",
    "        t_start = np.random.uniform(high=4*np.pi)\n",
    "        t = np.linspace(t_start, num_periods_big*4*np.pi + t_start, n_time_steps)\n",
    "\n",
    "\n",
    "        xgrid, ygrid, tgrid = np.meshgrid(x, y, t)\n",
    "\n",
    "        Phi = np.cos(w0*tgrid)\n",
    "\n",
    "        Phi[:width_small, :width_small,:] = np.cos(w1*tgrid[:width_small, :width_small,:]+np.pi/4)\n",
    "        scaled_Phi = (Phi.T - Phi.min()) / (Phi.max() - Phi.min())\n",
    "        data[i] = scaled_Phi\n",
    "\n",
    "    print(\"making done, saving to \", os.path.join(data_dir, file_name))\n",
    "    np.save(os.path.join(data_dir, file_name), data)\n",
    "    print(\"done\")\n",
    "    \n",
    "    return data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0c29534a86e0400ab9d457d2fe4f38dc",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2b\\train_data.npy\n",
      "done\n",
      "(100, 500, 16, 16)\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAS4AAAD4CAYAAABSUAvFAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAAUPklEQVR4nO3df6wlZX3H8ffHBUpBKMKi4u4qq0WMGlByu/6MtaXoQgloalLwF1bMhqb4o6lRjIma9J9SW6ut1M0tbNWWQFJF3djVhdga2qh0F1wQWJAVqVxAd1kakGpk995P/ziz9Py69869Z86ZmcvnZSZ3zszcZ77Mufv1mWeeeR7ZJiKiTZ5WdwAREUuVxBURrZPEFRGtk8QVEa2TxBURrXPYJE92hH7NR3L0JE85ES887Rd1hxABwH33H+DhR2Y1Shlv/J2jvf+R2VLH3nzbr7bb3jjK+ZZjoonrSI7mFTpzkqeciO3bd9UdQgQAG954/8hl7H9klv/a/txSx6466Z7VI59wGSaauCKi+QzMMVd3GAtK4oqIHsYccLlbxbqM1DgvaaOkuyXtkXRZVUFFRL3mSv6vLsuucUlaBVwBnAXMADskbbV9Z1XBRcTkGTPb8FcBR6lxbQD22L7X9hPAtcD51YQVEXWaw6WWuozSxrUG6H6EMQO8ov8gSZuATQBHctQIp4uISTAwW2NSKmOUxDWsr8jAf63taWAa4Fgd3+yrEREAtdamyhglcc0A67o+rwUeHC2ciKibgQMNb+MaJXHtAE6RtB54ALgAeGslUUVEbYxX7q2i7YOSLgW2A6uALbbvqCyyiKiHYbbZeWu0Dqi2twHbKoolIhqg03O+2dJzPiL6iNmhz96aI4krInp0GueTuCKiRTr9uJK4IqJl5lLjiog2SY0rIlrHiNmGj+qexBURA3KrGBGtYsQTXlV3GAtK4oqIHp0OqLlVjIiWSeN8RLSKLWbd7BpXs6OLiFrMoVJLGYvNTSHp9ZIelbSrWD62WJmpcUVEj07jfDWpYQlzU/yH7XPLlpsaV0T0ONQ4X2YpYSxzUyRxRcSAWavUAqyWtLNr2dRX1LC5KdYMOeWrJN0q6RuSXrJYfLlVjIgeS+w5/7DtqQX2l5mb4hbgebYfl3QO8FXglIVOmhpXRAyY89NKLSUsOjeF7cdsP16sbwMOl7R6oUKTuCKiR+cl66eVWkp4cm4KSUfQmZtia/cBkp4tScX6Bjp5af9ChY4yk/U64IvAs+mM9Dpt+zPLLS8imsGIAxW98jPf3BSSLin2bwbeAvyxpIPAL4EL7IWnGRqljesg8Ge2b5F0DHCzpBuGPOaMiBaxqbQD6rC5KYqEdWj9s8Bnl1LmKLP8PAQ8VKz/XNJuOk8LkrgiWq1859K6VPJUUdLJwMuBm4bs2wRsAjiSo6o4XUSMkam2xjUOIycuSU8Hvgx8wPZj/fttTwPTAMfq+IbP1hYRwMoeSFDS4XSS1tW2r6smpIiok9HKHUiweHx5FbDb9qeqCyki6tSZnqzZfdNHqQ++BngH8Ltdb3WfU1FcEVGbzoSwZZa6jPJU8T8Z3p0/IlrMULZXfG2aXR+MiFpkBNSIaBVbqXFFRLt0Guczy09EtErzx5xP4oqIHp3G+bRxRUTLrOie8xGx8qzonvMRsXJlJuuIaBUbDswlcUVEi3RuFZO4IqJl0nM+Ilol3SEiooVyqxgRLfSUGHO+rBee9gu2b981yVNGxBJ1nirmXcWIaJF0QI2IVsqtYkS0ylPiqaKkVcBO4AHb544eUkTU7anwVPH9wG7g2ArKioia2eJgwxPXSNFJWgv8PnBlNeFERBPMWaWWuoxa4/o08CHgmNFDiYgmaEMb17JrXJLOBfbavnmR4zZJ2ilp5779s8s9XURMUNNrXKNOCHuepPuAa+lMDPvP/QfZnrY9ZXvqxBOa3aktIv6/H9eKTFy2P2J7re2TgQuAf7P99soii4jazKFSS13Sjysiethw8KkwkKDtbwPfrqKsiKhf0xvnU+OKiB55VzEiWskNT1zNvpGNiFpU2TgvaaOkuyXtkXTZAsf9lqRZSW9ZrMzUuCKih11dG1fxLvMVwFnADLBD0lbbdw457nJge5lyU+OKiD5idu5ppZYSNgB7bN9r+wk6fT7PH3Lce4EvA3vLFJrEFREDbJVagNWH3owplk19Ra0B7u/6PFNse5KkNcCbgc1l48utYkT0WOK7ig/bnlpg/7CC3Pf508CHbc9K5c6bxBURvdxp56rIDLCu6/Na4MG+Y6aAa4uktRo4R9JB21+dr9AkrogYUOHrPDuAUyStBx6g83rgW7sPsL3+0LqkzwNfXyhpQRJXRPRx0ThfSVn2QUmX0nlauArYYvsOSZcU+0u3a3VL4oqIARXeKmJ7G7Ctb9vQhGX7XWXKTOKKiAFN7zmfxBURPewkrohoobxkHRGtU2Ub1zgkcUVEDyPmngoDCUbEytLwClcSV0T0SeN8RLRSw6tco85kfZykL0m6S9JuSa+qKrCIqM8SRoeoxag1rs8A37T9FklHAEdVEFNE1MjA3NwKvVWUdCzwOuBdAMUgYU9UE1ZE1MZAw9u4RrlVfD6wD/hHSd+XdKWko/sPkrTp0CBj+/bPjnC6iJgUu9xSl1ES12HAGcDnbL8c+F9gYCB829O2p2xPnXjCqhFOFxET45JLTUZJXDPAjO2bis9fopPIIqLVyjXM19k4v+zEZfunwP2STi02nQncucCvRERbNLzGNepTxfcCVxdPFO8F/mj0kCKiVgav1KeKALZ30RkvOiJWlBWcuCJihWp4z/kkrogYlMQVEa3Sgg6oSVwRMSADCUZE+6zkp4oRsTIpNa6IaJWaO5eWkcQVEX2UxvmIaKHUuCKidebqDmBhSVwR0Sv9uCKijfJUMSLap+GJq9nT1UZEDJEaV0QMyK1iRLSLySs/EdFCqXFFRNs0/VZxpMZ5SX8q6Q5Jt0u6RtKRVQUWETWqcLIMSRsl3S1pj6SBKQwlnS/pNkm7ijlYX7tYmctOXJLWAO8Dpmy/FFgFXLDc8iKiQSpKXJJWAVcAZwMvBi6U9OK+w74FnG77ZcC7gSsXK3fU7hCHAb8u6TDgKODBEcuLiJrJ5ZcSNgB7bN9r+wngWuD87gNsP24/OXTh0ZRIiaPMq/gA8FfAT4CHgEdtX99/nKRNRfVv5779s8s9XURM0pzKLbD60L/vYtnUV9Ia4P6uzzPFth6S3izpLuBf6dS6FjTKreIz6GTO9cBzgKMlvb3/ONvTtqdsT514wqrlni4iJmgJNa6HD/37Lpbp/qKGFD9Qo7L9FdsvAt4E/Pli8Y1yq/h7wI9t77N9ALgOePUI5UVEU1TXOD8DrOv6vJYFmpRs3wi8QNLqhQodJXH9BHilpKMkCTgT2D1CeRHRBNW2ce0ATpG0vpjx/gJga/cBkn6zyCFIOgM4Ati/UKHL7sdl+yZJXwJuAQ4C3wf6q4kR0UYV9eOyfVDSpcB2Oj0Ptti+Q9Ilxf7NwB8A75R0APgl8IddjfVDjdQB1fbHgY+PUkZENI8qHEjQ9jZgW9+2zV3rlwOXL6XMjA4REa2TV34iYlDDX/lJ4oqIXuUb3muTxBURg5K4IqJ1krgiok1EtU8VxyGJKyJ6pY0rIlopiSsiWieJKyLaJreKEdE+SVwR0SrOU8WIaKPUuCKibdLGFRHtk8QVEa2yhDkT65LEFRE9RG4VI6KFmp64Fh0BVdIWSXsl3d617XhJN0i6p/j5jPGGGRETVd0sP2NRZujmzwMb+7ZdBnzL9il0ps++rOK4IqJObU9cxTxnj/RtPh/4QrH+BTqTOEbESlDt9GRjsdzJMp5l+yGA4ucz5ztQ0qZD03Pv2z+7zNNFxES1vcY1KtvTh6bnPvGEVeM+XURUQHPllrosN3H9TNJJAMXPvdWFFBF1W6m3iluBi4r1i4CvVRNORNSu7G1ikxOXpGuA7wKnSpqRdDHwF8BZku4Bzio+R8RK0fDEtWgHVNsXzrPrzIpjiYgGSM/5iGglzTU7cyVxRUSvvGQdEW2UW8WIaJ8krohom9S4IqJ9krgiolUyy09EtE36cUVEO7nZmWvso0NERPtU+ZK1pI2S7pa0R9LAoKOS3ibptmL5jqTTFyszNa6I6FVhB1RJq4Ar6LzTPAPskLTV9p1dh/0Y+G3b/yPpbGAaeMVC5SZxRcSAChvnNwB7bN8LIOlaOiMoP5m4bH+n6/jvAWsXKzSJKyIGLCFxrZa0s+vztO3prs9rgPu7Ps+wcG3qYuAbi500iSsiepmlNM4/bHtqgf2a5wyDB0q/QydxvXaxkyZxRcSACrtDzADruj6vBR4cOJ90GnAlcLbt/YsVmqeKETGouoEEdwCnSFov6QjgAjojKD9J0nOB64B32P5hmUJT44qIHlV2QLV9UNKlwHZgFbDF9h2SLin2bwY+BpwA/L0kgIOL3H4mcUVEH7vSgQRtbwO29W3b3LX+HuA9SymzzJjzWyTtlXR717ZPSrqr6DD2FUnHLeWkEdFwDR9zvkwb1+eBjX3bbgBeavs04IfARyqOKyJq1PrpyWzfCDzSt+162weLj6U6jEVESxiYc7mlJlU8VXw3C3QYk7RJ0k5JO/ftn63gdBExdivgVnFekj4KHASunu8Y29O2p2xPnXjCqlFOFxET0vRbxWU/VZR0EXAucKbd8DEwImJJVuT0ZJI2Ah+m80b3L6oNKSJq1YLpycp0h7gG+C5wqqQZSRcDnwWOAW6QtEvS5gULiYjW6HRAdamlLovWuGxfOGTzVWOIJSKaImPOR0Tb1FmbKiOJKyJ6taCNK4krIvpU+67iOCRxRcSg3CpGRKtkQtiIaKXUuCKidZqdt5K4ImKQ5pp9r5jEFRG9TDqgRkS7iHpf5ykjiSsiBiVxRUTrJHFFRKukjSsi2ihPFSOiZZxbxYhoGZPEFREt1Ow7xSSuiBjU9H5cZcac3yJpr6Tbh+z7oCRLWj2e8CKiFna5pSZl5lX8PLCxf6OkdcBZwE8qjiki6mTD7Fy5pSaLJi7bNwKPDNn1N8CHaPx75BGxZA2vcS13XsXzgAds3yppsWM3AZsAnrsmTWoRrdDwNq4lZxJJRwEfBd5Q5njb08A0wNTpRzb7akRE0XO+2f9Ul1MFegGwHjhU21oL3CJpg+2fVhlcRNTB4Gb3h1hy4rL9A+CZhz5Lug+Ysv1whXFFRF1MrQ3vZZTpDnEN8F3gVEkzki4ef1gRUauGN86Xeap4oe2TbB9ue63tq/r2n5zaVsQKU2HikrRR0t2S9ki6bMj+F0n6rqRfSfpgmTLzmC8i+lRXm5K0CriCTp/PGWCHpK227+w67BHgfcCbypZbpgNqRDyVGJibK7csbgOwx/a9tp8ArgXO7zmdvdf2DuBA2RCTuCJiUPlbxdWSdnYtm/pKWgPc3/V5ptg2ktwqRkQfL+Wp4sO2pxbYP6yH+sj3oUlcEdHL4Or6cc0A67o+rwUeHLXQ3CpGxKA5l1sWtwM4RdJ6SUcAFwBbRw0vNa6IGFTRU0XbByVdCmwHVgFbbN8h6ZJi/2ZJzwZ2AscCc5I+ALzY9mPzlZvEFRG97LJPDEsW523Atr5tm7vWf0rnFrK0JK6IGLTSRoeIiJXOeHa27iAWlMQVEb1W6LA2EbHSrbRhbSJiZTPg1LgiolW8AgcSjIiVr+mN8/IEH3tK2gf89zy7VwNNGNcrcfRKHL2aHsfzbJ84SsGSvlmUX8bDtgemLxy3iSauhUjaucjLmokjcSSOhsVRl7yrGBGtk8QVEa3TpMQ1XXcAhcTRK3H0ShwN0Jg2roiIsppU44qIKCWJKyJaZ6KJq8T8apL0t8X+2ySdMYYY1kn6d0m7Jd0h6f1Djnm9pEcl7SqWj1UdR9e57pP0g+I8O4fsH+s1kXRq13/nLkmPFQO5dR8ztushaYukvZJu79p2vKQbJN1T/HzGPL+74N9TBXF8UtJdxXX/iqTj5vndBb/DCuL4hKQHuq7/OfP8bmXXo/FsT2ShM/rhj4DnA0cAt9IZ5bD7mHOAb9AZYP+VwE1jiOMk4Ixi/Rjgh0PieD3w9Qldl/uA1QvsH/s16fuOfkqnE+NErgfwOuAM4PaubX8JXFasXwZcvpy/pwrieANwWLF++bA4ynyHFcTxCeCDJb67yq5H05dJ1rgWnV+t+PxFd3wPOE7SSVUGYfsh27cU6z8HdlPBdEljNPZr0uVM4Ee253u7oXK2b6QzIWi384EvFOtfYPhEoWX+nkaKw/b1tg8WH7/HEkfprCqOkiq9Hk03ycRVZn61sczBNh9JJwMvB24asvtVkm6V9A1JLxlXDHRexr9e0s1D5qSDyV6TC4Br5tk3qesB8CzbD0Hn/2iAZw45ZqJ/K8C76dR8h1nsO6zCpcUt65Z5bp0nfT1qNcnEVWZ+tbHMwTaMpKcDXwY+4MFB+W+hc7t0OvB3wFfHEUPhNbbPAM4G/kTS6/pDHfI7lV+TYgaW84B/GbJ7ktejrEn+rXwUOAhcPc8hi32Ho/oc8ALgZcBDwF8PC3PIthXb12mSiavM/GpjmYOtn6TD6SStq21f17/f9mO2Hy/WtwGHSyr70umS2H6w+LkX+AqdKn+3iVwTOv/obrH9syExTux6FH526Ha4+Ll3yDGT+lu5CDgXeJuLxqR+Jb7Dkdj+me1ZdyY7/Id5yp/U30kjTDJxlZlfbSvwzuJJ2iuBRw/dMlRFkoCrgN22PzXPMc8ujkPSBjrXaX+VcRRlHy3pmEPrdBqDb+87bOzXpHAh89wmTup6dNkKXFSsXwR8bcgxY5mvr5ukjcCHgfNs/2KeY8p8h6PG0d2m+eZ5yh/79WiUST4JoPOE7Id0nn58tNh2CXBJsS7gimL/D4CpMcTwWjpV6NuAXcVyTl8clwJ30Hky8z3g1WO6Hs8vznFrcb66rslRdBLRb3Rtm8j1oJMsHwIO0Kk1XAycAHwLuKf4eXxx7HOAbQv9PVUcxx467UaH/k4298cx33dYcRz/VHz3t9FJRieN+3o0fckrPxHROuk5HxGtk8QVEa2TxBURrZPEFRGtk8QVEa2TxBURrZPEFRGt83+f3/I4MS3BoAAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "87b383db43a94dfdba1fcd4b6b86e18c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=10.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2b\\val_data.npy\n",
      "done\n",
      "4\n",
      "Making data\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f314884d6d224c94978b96f9708e3523",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=10.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "making done, saving to  ./data/toy2b\\test_data.npy\n",
      "done\n"
     ]
    }
   ],
   "source": [
    "n_train_points = 100\n",
    "n_val_points = 10\n",
    "n_test_points = 10\n",
    "n_time_steps = 500\n",
    "dim = 16\n",
    "width_small = int(dim/4)\n",
    "\n",
    "# params\n",
    "w0 = 0.5\n",
    "w1 = 1.0\n",
    "# width_small = 8\n",
    "num_periods_big = 8\n",
    "\n",
    "\n",
    "# paths\n",
    "data_dir = './data/toy2b'\n",
    "result_dir = './result/toy2b'\n",
    "\n",
    "\n",
    "x = np.arange(dim)\n",
    "y = np.arange(dim)\n",
    "train_data = make_data(n_train_points, 'train_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "print(train_data.shape)\n",
    "plt.imshow(train_data[0,0])\n",
    "plt.colorbar()\n",
    "plt.show()\n",
    "val_data = make_data(n_val_points, 'val_data.npy', data_dir = data_dir,width_small=width_small,dim=dim) \n",
    "test_data = make_data(n_test_points, 'test_data.npy', data_dir=data_dir,width_small=width_small,dim=dim) \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(100, 500, 8, 8)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.colorbar.Colorbar at 0x2042fe6a610>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAScAAAD4CAYAAACuRSAPAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8vihELAAAACXBIWXMAAAsTAAALEwEAmpwYAAAT40lEQVR4nO3df6xfdX3H8eeLSxGLoNOiYlulug7DFgF3V2Nw/gCRomhnZmJhamSajmU1mi1T3B8umf/MmBhMRJumVlxkdA7Bda5SiQ7RqVhAREopu6vOXqqDwgzCHOXe+9of33PZt5d7v99z7Tnf7/ne83okJ3zPDz/nfUN4+/l8zueHbBMR0TTHDTuAiIj5JDlFRCMlOUVEIyU5RUQjJTlFRCMdX0ehK5495tNXL6uj6KjJfXctH3YIsQj/y2Mc8eM6ljIufN1Jfujh6VLP3n7X47ttrz+W9y1WLcnp9NXL+P7u1XUUHTW58AVnDzuEWIRb/fVjLuOhh6f5/u4Xlnp27LR/X3HML1ykWpJTRDSfgRlmhh3GgpKcIlrKmCdcrlk3DElOES2WmlNENI4x0w2evpbkFNFiMyQ5RUTDGJhOcoqIJkrNKSIax8AT6XOKiKYxbnSzrtTcOknrJe2XNCHpirqDiogBMEyXPIahb3KSNAZcBVwEnAlcIunMugOLiHp1RoiXO4ahTM1pHTBh+4DtI8AOYEO9YUVE/cR0yWMYyvQ5rQQOdp1PAq+Y+5CkTcAmgBeuTFdWRNN1OsSHk3jKKFNzmi/6p7RCbW+1PW57/NTnjB17ZBFRq844p9GuOU0C3eufrAIO1RNORAzSTINrTmWS0x5graQ1wP3ARuDSWqOKiNrN1pyaqm9ysj0laTOwGxgDttveW3tkEVErI6YbvFJ3qZ5r27uAXTXHEhEDNurNuohYgow44uZ+vEpyimipziDMEW/WRcTSNNId4hGxNNli2s2tOTU3soio3QwqdfTTb3EASc+U9M+Sfihpr6TL+pWZmlNES3U6xI89BXQtDnABnUHbeyTttH1P12N/Btxj+82STgX2S7qmmK87r9ScIlpqtkO8zNFHmcUBDJwsScAzgIeBqV6FpuYU0WLT5cc5rZB0W9f5Vttbi99lFgf4FLCTztS3k4G32+65GkuSU0RLLXKE+GHb4wvcK7M4wIXAncB5wEuAmyR9y/YjC70wzbqIFpvxcaWOPsosDnAZcL07JoAfAy/tVWiSU0RLdSb+Hlfq6OPJxQEknUBncYCdc575KXA+gKTnAWcAB3oVmmZdREsZ8UQF01cWWhxA0uXF/S3AR4GrJf2ITjPwQ7YP9yo3ySmipWwqG4Q53+IARVKa/X0IeMNiykxyimitcgMshyXJKaKlTHU1pzokOUW02MgvNhcRS49RFpuLiObpbA3V3BRQZsff7ZIekHT3IAKKiEFp9qaaZRqcVwPra44jIgbMVDZCvBZldl+5RdLpA4glIgasFSthZjvyiNFia2i1ojIqyyLF8glbAcbPOvEp25VHRLN0OsSz+0pENE6z1xBPcopoqU6HeHP7nMoMJbgW+C5whqRJSe+pP6yIGISKlkypRZmvdZcMIpCIGKyMEI+IxsqOvxHRODY8MZPkFBEN02nWJTlFRAO1YoR4RIyWkR9KEBFLlSqb+CtpvaT9kiYkXTHP/b+UdGdx3C1pWtKze5WZ5BTRYjPFOuL9jl4kjQFXARcBZwKXSDqz+xnbH7d9tu2zgQ8D37T9cK9y06yLaKnO17pK5tatAyZsHwCQtAPYANyzwPOXANf2KzQ1p4iWmh2EWeboYyVwsOt8srj2FJKW01kf7kv9Ck3NKaLFFrE11ApJt3Wdby1WIgHmLWShlUneDPxbvyYdJDlFtNYiv9Ydtj2+wL1JYHXX+Srg0ALPbqREkw6SnCJaraJBmHuAtZLWAPfTSUCXzn1I0jOB1wDvKFNoklNES9liqoLkZHtK0mZgNzAGbLe9V9Llxf3ZbcnfCnzN9mNlyk1yimixqgZh2t4F7Jpzbcuc86vpbJhSSpJTREs1fYR4klNEiyU5RUTjZLG5iGisRYxzGri+yUnSauDvgOcDM3QGX32y7sAiol42TI34YnNTwF/YvkPSycDtkm6yvdC8mYgYESPdrLP9M+Bnxe9fStpHZ95MklPECFtSfU6STgfOAW6d5162I48YMW5wcird4JT0DDoziT9g+5G5921vtT1ue/zU5zR3i+OI+H9VrOdUl1JVHEnL6CSma2xfX29IETEI9oj3OUkS8Flgn+1P1B9SRAyGmG7w17oykZ0LvBM4r2sN4DfWHFdEDICtUscwlPla923mX0wqIkZY5tZFRDO50+/UVElOES020tNXImJpcsM7xJOcIloszbqIaKQmjxBPcopoKTvJKSIaqslDCZrbGxYRtbPLHf1IWi9pv6QJSVcs8Mxri0HceyV9s1+ZqTlFtJQRMxV8rZM0BlwFXEBng809knZ2r/km6VnAp4H1tn8q6bn9yk3NKaLFXPLoYx0wYfuA7SPADmDDnGcuBa63/VMA2w/0KzTJKaKtvKi5dSsk3dZ1bOoqaSVwsOt8srjW7beA35B0s6TbJb2rX3hp1kW0WflxTodtjy9wb75e9bklHw/8LnA+8HTgu5K+Z/u+hV6Y5BTRYhUNJZgEVnedrwIOzfPM4WIr8sck3QKcBSyYnNKsi2gpAzMzKnX0sQdYK2mNpBOAjcDOOc/8E/D7ko6XtBx4BbCvV6GpOUW0lYEKak62pyRtBnYDY8B223slXV7c32J7n6QbgbvobDG3zfbdvcpNcoposarm1tneBeyac23LnPOPAx8vW2aSU0SbZeJvRDTP8JbgLaPMBgcnArcATyuev872X9cdWEQMwIjXnB4HzrP9aLFF1LclfdX292qOLSLqZHD/L3FDU2aDAwOPFqfLiqPB+TYiymtucio1zknSmKQ7gQeAm2zPux357ND2Bx+arjjMiKhFRZPr6lAqOdmetn02nZGf6yT9zjzPZDvyiFEz6slplu1fADcD6+sIJiIGaHYQZpljCPomJ0mnFmuxIOnpwOuBe2uOKyIGoKrF5upQ5mvdacDniwWljgO+aPsr9YYVEQMx4l/r7gLOGUAsETFgavB394wQj2irIXZ2l5HkFNFaw+vsLiPJKaLNUnOKiEaaGXYAC0tyimirihabq0uSU0SL5WtdRDRTg5NTNjiIiEaqpeZ0313LufAFZ9dRdERUqKpmnaT1wCfpbHCwzfbfzrn/Wjo7sPy4uHS97b/pVWaadRFtZSqZvlJMbbsKuIDO/nR7JO20fc+cR79l++Ky5aZZF9Fm1SyZsg6YsH3A9hFgB7DhWENLcopoMbncAayYXUyyODZ1FbMSONh1Pllcm+uVkn4o6auSfrtfbGnWRbRZ+T6nw7bHF7g3X9twbsl3AC8q9iJ4I/BlYG2vF6bmFNFm1TTrJoHVXeergENHvcZ+xPajxe9dwDJJK3oVmuQU0VJlm3QlvujtAdZKWiPpBGAjsPOod0nPl6Ti9zo6ueehXoWmWRfRZhV8rbM9JWkzsJvOUILttvdKury4vwV4G/CnkqaAXwEbi52dFpTkFNFiVY1zKppqu+Zc29L1+1PApxZTZpJTRJs1ePpKklNEW5XrTxqa0h3ixcaaP5CUzQ0ilooG71u3mJrT+4F9wCk1xRIRA6YGLzZXdjvyVcCbgG31hhMR0VG2WXcl8EF6LOopadPs0PYneLyK2CKibg1u1pXZ8fdi4AHbt/d6zvZW2+O2x5fxtMoCjIiaVDcIsxZl+pzOBd5SzIc5EThF0hdsv6Pe0CKidqP8tc72h22vsn06nWHp30hiilgiGtysyziniJYSzf5at6jkZPtm4OZaIomIwWr4IMzUnCLaLMkpIhopySkimijNuohopiSniGgcL6GvdRGxxKTmFBFNlD6niGimBien7L4S0VZlp66USGCS1kvaL2lC0hU9nvs9SdOS3tavzCSniJYS1axKIGkMuAq4CDgTuETSmQs89zE6u7T0leQU0WIVLZmyDpiwfcD2EWAHsGGe594HfAl4oExsSU4RbVa+WbdidjHJ4tjUVcpK4GDX+WRx7UmSVgJvBbZQUjrEI9qsfIf4YdvjC9ybb2fOuSVfCXzI9nSx8W9fSU4RbVXdqgSTwOqu81XAoTnPjAM7isS0AnijpCnbX16o0CSniDarJjntAdZKWgPcT2dRykuPeo29Zva3pKuBr/RKTJDkFNFqVUxfsT0laTOdr3BjwHbbeyVdXtwv3c/ULckposWqGiFuexewa861eZOS7XeXKTPJKaKthrg+eBmlkpOknwC/BKaBqR699hExSkY9ORVeZ/twbZFExEDNjhBvqjTrIlpMM83NTmVHiBv4mqTb54wMfVK2I48YMRVO/K1D2ZrTubYPSXoucJOke23f0v2A7a3AVoBT9OzmpuOIeFKTm3Wlak62DxX/fAC4gc5Ev4gYdQ2uOfVNTpJOknTy7G/gDcDddQcWEfWraFWCWpRp1j0PuKGYE3M88Pe2b6w1qogYjAY36/omJ9sHgLMGEEtEDFJ2X4mIJso4p4hoLjc3OyU5RbRYak4R0TxLYeJvRCxN6RCPiEZKcoqI5jHpEI+IZkqHeEQ0U4OTUzbVjGipqrYjB5C0XtJ+SROSrpjn/gZJd0m6s1ha6VX9ykzNKaKt7EoWm5M0BlwFXEBnD7s9knbavqfrsa8DO21b0suALwIv7VVuak4RbVbNkinrgAnbB2wfAXYAG456jf2o/WTv+0llSk1yimixRTTrVsyudFsc3SvirgQOdp1PFteOfpf0Vkn3Av8C/HG/2NKsi2grA+WbdYd77LqkBUo/+oJ9A53ll14NfBR4fa8XpuYU0WbVNOsmgdVd56uAQwu+srPE90skrehVaJJTRItV9LVuD7BW0hpJJwAbgZ1HvUf6TRUrVkp6OXAC8FCvQtOsi2ixKr7W2Z6StBnYDYwB223vlXR5cX8L8IfAuyQ9AfwKeHtXB/m8kpwi2qrCVQls7wJ2zbm2pev3x4CPLabMUs06Sc+SdJ2keyXtk/TKxbwkIpqnMwjTpY5hKFtz+iRwo+23FW3K5TXGFBGDMsqrEkg6BXg18G6AYpDVkXrDiohBGFatqIwyzboXAw8Cn5P0A0nbiv3rjpLtyCNGTMO3Iy+TnI4HXg58xvY5wGPAUyb22d5qe9z2+DKeVnGYEVG9zty6MscwlElOk8Ck7VuL8+voJKuIGHV2uWMI+iYn2z8HDko6o7h0PnBPj/9JRIyCYlPNMscwlP1a9z7gmuJL3QHgsvpCioiBaXCHeKnkZPtOYKFJfxExqpqbmzJCPKLNNNPcgU5JThFtZUZ7EGZELE1ieFNTykhyimizJKeIaKQkp4honPQ5RURT5WtdRDTQ8KamlJHkFNFWJskpIhqqua267L4S0WZVLdMrab2k/ZImJD1lSSVJfyTpruL4jqSz+pWZmlNEm1XQrJM0BlwFXEBniaU9knba7l695MfAa2z/t6SLgK3AK3qVm+QU0VY2TFfSrlsHTNg+ACBpB7CBrqWVbH+n6/nv0dl4s6c06yLarPxicytml+Eujk1dpawEDnadTxbXFvIe4Kv9QkvNKaLNyjfrDtteaNkkzVfyvA9Kr6OTnF7V74VJThFtZaCa9cEngdVd56uAQ3MfkvQyYBtwke2eW5FDmnURLWbwTLmjtz3AWklritVyNwI7ux+Q9ELgeuCdtu8rE11qThFtZSrpELc9JWkzsBsYA7bb3ivp8uL+FuAjwHOAT0sCmOrRTATKbap5BvAPXZdeDHzE9pW/zh8SEQ1S0Qhx27uAXXOuben6/V7gvYsps29ysr0fOBueHM9wP3DDYl4SEQ21hKavnA/8h+3/rCOYiBikpTXxdyNw7Xw3inEPmwBOZPkxhhURtTPQ4CVTSn+tK3rh3wL843z3sx15xAhq8I6/i6k5XQTcYfu/6gomIgapsukrtVhMcrqEBZp0ETGCDO4/hmloSiUnScvpzDj+k3rDiYiBqmaEeC3Kbkf+P3QGUEXEUrKEvtZFxFJhN/prXZJTRJul5hQRzWM8PT3sIBaU5BTRVtUtmVKLJKeINhv1oQQRsfQYcGpOEdE4dmpOEdFMTe4Ql2v4lCjpQWCxy6qsAA5XHkwzLNW/LX/X8LzI9qnHUoCkG+n8rWUctr3+WN63WLUkp1+HpNv6Lds5qpbq35a/K+qUDQ4iopGSnCKikZqUnLYOO4AaLdW/LX9X1KYxfU4REd2aVHOKiHhSklNENFIjkpOk9ZL2S5qQdMWw46mCpNWS/lXSPkl7Jb1/2DFVSdKYpB9I+sqwY6mSpGdJuk7SvcW/u1cOO6a2GnqfU7FR5310lgGepLPv+iW27xlqYMdI0mnAabbvkHQycDvwB6P+d82S9OfAOHCK7YuHHU9VJH0e+JbtbcWOQ8tt/2LIYbVSE2pO64AJ2wdsHwF2ABuGHNMxs/0z23cUv38J7ANWDjeqakhaBbwJ2DbsWKok6RTg1cBnAWwfSWIaniYkp5XAwa7zSZbIf8SzJJ0OnAPcOuRQqnIl8EGgubNGfz0vBh4EPlc0WbdJOmnYQbVVE5KT5rm2ZMY3SHoG8CXgA7YfGXY8x0rSxcADtm8fdiw1OB54OfAZ2+cAjwFLog90FDUhOU0Cq7vOVwGHhhRLpSQto5OYrrF9/bDjqci5wFsk/YROE/w8SV8YbkiVmQQmbc/WcK+jk6xiCJqQnPYAayWtKTogNwI7hxzTMZMkOn0X+2x/YtjxVMX2h22vsn06nX9X37D9jiGHVQnbPwcOSjqjuHQ+sCQ+YIyioa/nZHtK0mZgNzAGbLe9d8hhVeFc4J3AjyTdWVz7K9u7hhdSlPA+4Jri/ygPAJcNOZ7WGvpQgoiI+TShWRcR8RRJThHRSElOEdFISU4R0UhJThHRSElOEdFISU4R0Uj/BxD9M/fkWB0QAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "print(train_data.shape)\n",
    "plt.imshow(train_data[2,0])\n",
    "plt.colorbar()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def animate(snapshots, normalize = True, file_name = \"animation.gif\"):\n",
    "    \"\"\"\n",
    "    Makes an animation of snapshots in time\n",
    "    \n",
    "    inputs:\n",
    "    snapshots: np.array of size (n_time_steps,1, dim, dim)\n",
    "    normalize = True: whether to fix axis between 0 and 1 or not\n",
    "    file_name = \"animation.gif\": file name of where to save gif\n",
    "    \n",
    "    outputs:\n",
    "    no returned output\n",
    "    gif saved to file_name\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "    fps = 30\n",
    "    nSeconds = len(snapshots)/fps\n",
    "    \n",
    "    # First set up the figure, the axis, and the plot element we want to animate\n",
    "    fig = plt.figure( figsize=(8,8) )\n",
    "\n",
    "    a = snapshots[0,:,:,:][0].T\n",
    "    if normalize:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=0.0, vmax=1.0)\n",
    "    else:\n",
    "        im = plt.imshow(a, interpolation='none', aspect='auto', vmin=np.min(snapshots), vmax=np.max(snapshots))\n",
    "    plt.colorbar()\n",
    "\n",
    "    print(\"Animating, may take a little while...\")\n",
    "\n",
    "    def animate_func(i):\n",
    "        if i % fps == 0:\n",
    "            print( '.', end ='' )\n",
    "\n",
    "        im.set_array(snapshots[i,:,:,:,][0].T)\n",
    "        return [im]\n",
    "\n",
    "    anim = animation.FuncAnimation(\n",
    "                                   fig,\n",
    "                                   animate_func,\n",
    "                                   frames = int(nSeconds * fps),\n",
    "                                   interval = 1000 / fps, # in ms\n",
    "                                   )\n",
    "    writergif = animation.PillowWriter(fps=30)\n",
    "    anim.save(file_name, writer=writergif)\n",
    "\n",
    "    print('Done! gif saved to ', file_name)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Animating, may take a little while...\n",
      ".."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 751, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 720, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 705, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Error in callback <function flush_figures at 0x000001E2C30F44C0> (for post_execute):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 251, in saving\n",
      "    yield self\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1141, in save\n",
      "    anim._draw_next_frame(d, blit=False)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1177, in _draw_next_frame\n",
      "    self._post_draw(framedata, blit)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1202, in _post_draw\n",
      "    self._fig.canvas.draw_idle()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2012, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 407, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 1863, in draw\n",
      "    mimage._draw_list_compositing_images(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\cbook\\deprecation.py\", line 411, in wrapper\n",
      "    return func(*inner_args, **inner_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 2747, in draw\n",
      "    mimage._draw_list_compositing_images(renderer, self, artists)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\image.py\", line 131, in _draw_list_compositing_images\n",
      "    a.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1169, in draw\n",
      "    tick.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 291, in draw\n",
      "    artist.draw(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\artist.py\", line 41, in draw_wrapper\n",
      "    return draw(artist, renderer, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\text.py\", line 725, in draw\n",
      "    textrenderer.draw_text(gc, x, y, clean_line,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 195, in draw_text\n",
      "    font = self._get_agg_font(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_agg.py\", line 272, in _get_agg_font\n",
      "    fname = findfont(prop)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\font_manager.py\", line 1314, in findfont\n",
      "    return os.path.realpath(filename)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 647, in realpath\n",
      "    path = _getfinalpathname(path)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3418, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-4e619ad7cffb>\", line 1, in <module>\n",
      "    animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))\n",
      "  File \"<ipython-input-5-2e1703cf0959>\", line 45, in animate\n",
      "    anim.save(file_name, writer=writergif)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 1145, in save\n",
      "    writer.grab_frame(**savefig_kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\contextlib.py\", line 131, in __exit__\n",
      "    self.gen.throw(type, value, traceback)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 253, in saving\n",
      "    self.finish()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\animation.py\", line 554, in finish\n",
      "    self._frames[0].save(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2148, in save\n",
      "    fp = builtins.open(filename, \"w+b\")\n",
      "FileNotFoundError: [Errno 2] No such file or directory: './result/toy2a\\\\train_data.gif'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3338, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3435, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2923, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3146, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2877, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2928, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\events.py\", line 89, in trigger\n",
      "    func(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 121, in flush_figures\n",
      "    return show(True)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\ipykernel\\pylab\\backend_inline.py\", line 41, in show\n",
      "    display(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\display.py\", line 313, in display\n",
      "    format_dict, md_dict = format(obj, include=include, exclude=exclude)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 180, in format\n",
      "    data = formatter(obj)\n",
      "  File \"<decorator-gen-2>\", line 2, in __call__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 224, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\formatters.py\", line 341, in __call__\n",
      "    return printer(obj)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 248, in <lambda>\n",
      "    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\pylabtools.py\", line 132, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\backend_bases.py\", line 2195, in print_figure\n",
      "    bbox_inches = self.figure.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\figure.py\", line 2506, in get_tightbbox\n",
      "    bbox = a.get_tightbbox(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axes\\_base.py\", line 4155, in get_tightbbox\n",
      "    bb_xaxis = self.xaxis.get_tightbbox(\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1111, in get_tightbbox\n",
      "    self._update_label_position(renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2058, in _update_label_position\n",
      "    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 2042, in _get_tick_boxes_siblings\n",
      "    ticks_to_draw = axx.xaxis._update_ticks()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\axis.py\", line 1022, in _update_ticks\n",
      "    major_labels = self.major.formatter.format_ticks(major_locs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 249, in format_ticks\n",
      "    self.set_locs(values)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 780, in set_locs\n",
      "    self._compute_offset()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\matplotlib\\ticker.py\", line 793, in _compute_offset\n",
      "    lmin, lmax = locs.min(), locs.max()\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\numpy\\core\\_methods.py\", line 43, in _amin\n",
      "    return umr_minimum(a, axis, None, out, keepdims, initial, where)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2045, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1170, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1503, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 1461, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 708, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\inspect.py\", line 754, in getmodule\n",
      "    os.path.realpath(f)] = module.__name__\n",
      "  File \"C:\\Users\\16kat\\anaconda3\\lib\\ntpath.py\", line 664, in realpath\n",
      "    if _getfinalpathname(spath) == path:\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "animate(train_data[0].reshape(n_time_steps,1, dim, dim), file_name = os.path.join(result_dir,'train_data.gif'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
